"use client";

import { useEffect } from "react";

/** After the page has loaded, the first episode gets this long to itself. */
export const SERVICE_WORKER_DELAY_MS = 3_000;

/**
 * Registers /sw.js (generated by scripts/finish-export.mjs) once the page has
 * loaded and the main thread is idle, so installing the worker and its small
 * offline shell never competes with the first episode. Production exports
 * only: `next dev` has no sw.js. FLOW_SERVICE_WORKER=off at build time skips
 * registration, and the sw.js of that build retires any worker already
 * installed (docs/deploy.md).
 */
export function ServiceWorkerRegistration(): null {
  useEffect(() => {
    if (process.env.NODE_ENV !== "production") return;
    if (process.env.NEXT_PUBLIC_SERVICE_WORKER === "off") return;
    if (!("serviceWorker" in navigator)) return;

    let cancelled = false;
    let cancelIdle: (() => void) | null = null;
    let timer: number | null = null;

    const register = () => {
      if (cancelled) return;
      navigator.serviceWorker.register("/sw.js", { scope: "/" }).catch(() => {
        // Nothing depends on the worker: without it the site works as before,
        // minus the offline page.
      });
    };
    const whenIdle = () => {
      if (typeof window.requestIdleCallback === "function") {
        const handle = window.requestIdleCallback(register, { timeout: 5_000 });
        cancelIdle = () => window.cancelIdleCallback(handle);
      } else {
        register();
      }
    };
    const schedule = () => {
      timer = window.setTimeout(whenIdle, SERVICE_WORKER_DELAY_MS);
    };

    if (document.readyState === "complete") schedule();
    else window.addEventListener("load", schedule, { once: true });

    return () => {
      cancelled = true;
      window.removeEventListener("load", schedule);
      if (timer !== null) window.clearTimeout(timer);
      cancelIdle?.();
    };
  }, []);

  return null;
}
