"use client";

import {
  applyIntentPage,
  applyRecommendedPage,
  classifySeriesEnd,
  createCatalogIntentService,
  createDeterministicFeedSource,
  createLocalStorageResumeStore,
  createLocalStorageTasteStore,
  createRecommendationService,
  createWatchProgressThrottle,
  createWebPerfTiming,
  extendFeedPage,
  finishedLastEpisode,
  fromFeedCatalogPayload,
  getPrefetchIds,
  isNearEnd,
  isResumable,
  materializeFeedItems,
  needsExtension,
  pageStartingAt,
  placeNextInSeries,
  resumeLanding,
  shouldPersistResume,
  type CatalogIntentService,
  type ContentItem,
  type FeedCatalog,
  type FeedCatalogPayload,
  type FeedSource,
  type IntentChipId,
  type RecommendationService,
  type ResumeLanding,
  type ResumeSnapshot,
  type SeriesEndKind,
} from "@project-flow/feed-domain";
import { createLocalFeatureFlags } from "@project-flow/shared";
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactElement,
} from "react";

import {
  getAnalyticsClient,
  getAnalyticsTransport,
  getAnonymousUserId,
  getSessionId,
} from "@/lib/analytics";
import {
  captureAcquisitionFromLocation,
  createShareId,
  isDiagEnabled,
  loadAcquisitionContext,
} from "@/lib/session";

import { LaunchDiagPanel } from "@/features/diagnostics/LaunchDiagPanel";
import { patchLaunchDiagnostics } from "@/features/diagnostics/launchDiagnostics";

import { ContinueStrip } from "./ContinueStrip";
import type { FeedItemHandlers } from "./FeedItemView";
import { FeedScroller } from "./FeedScroller";
import { FeedStage } from "./FeedStage";
import { IntentSheet } from "./IntentSheet";
import { SeriesEnd } from "./SeriesEnd";
import {
  ERROR_SKIP_DELAY_MS,
  buildShareUrl,
  firstPlayStartMode,
  shouldShowPlayGate,
} from "./feedLogic";
import { createProgressStore, createStableHandlers } from "./progressStore";
import styles from "./feed.module.css";

/** Static file generated by app/catalog/feed.json/route.ts. */
export const FEED_CATALOG_URL = "/catalog/feed.json";
/**
 * Build the page even when nothing has played yet. Long on purpose: measured
 * on a throttled phone (1.6 Mbps, 4x CPU), first play takes about 9 s, and a
 * 4 s fallback parsed the catalog right in the middle of it. A refused
 * autoplay or a playback error schedules the page immediately instead.
 */
const CATALOG_FALLBACK_DELAY_MS = 20_000;

type FeedAppProps = {
  /** Target episode and the one after it, inlined in the page. */
  initial: FeedCatalogPayload;
  /** Deep-link starting content (watch route). */
  initialContentId?: string | undefined;
  deepLinkRoute?: string | undefined;
  catalogUrl?: string;
};

/** The catalog the feed currently knows: the first-frame items, then the full one. */
type FeedData = {
  catalog: FeedCatalog;
  source: FeedSource;
  ordered: ContentItem[];
  complete: boolean;
};

function feedDataFrom(catalog: FeedCatalog, complete: boolean): FeedData {
  const source = createDeterministicFeedSource(catalog);
  return {
    catalog: source.loadCatalog(),
    source,
    ordered: source.getOrderedItems(),
    complete,
  };
}

/** Runs when the main thread is free, so work never competes with first play. */
function whenIdle(callback: () => void): () => void {
  if (typeof window.requestIdleCallback === "function") {
    const handle = window.requestIdleCallback(callback, { timeout: 2_000 });
    return () => window.cancelIdleCallback(handle);
  }
  const timer = window.setTimeout(callback, 200);
  return () => window.clearTimeout(timer);
}

/** A move to another episode whose first frame is still to come (MP-1). */
type PendingTransition = {
  toContentId: string;
  kind: "swipe" | "auto_continue" | "error_skip";
  /** performance.now() when the move started. */
  startedAt: number;
};

function episodeCountOf(catalog: FeedCatalog, item: ContentItem): number | null {
  return catalog.series.find((series) => series.id === item.seriesId)?.totalEpisodes ?? null;
}

function hashSeed(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function FeedApp({
  initial,
  initialContentId,
  deepLinkRoute,
  catalogUrl = FEED_CATALOG_URL,
}: FeedAppProps): ReactElement {
  const analytics = useMemo(() => getAnalyticsClient(), []);
  const sessionId = useMemo(() => getSessionId(), []);
  const anonymousUserId = useMemo(() => getAnonymousUserId(), []);
  const locale = typeof navigator !== "undefined" ? navigator.language : "en";
  const flags = useMemo(
    () =>
      createLocalFeatureFlags({
        FEED_V0: true,
        RECOMMENDATION_V0: true,
        RECOMMENDATION_DIVERSITY_V0: true,
        RECOMMENDATION_EXPLORATION_V0: true,
        INTENT_LAYER: true,
        INTENT_CHIPS_V0: true,
      }),
    [],
  );

  const [feed, setFeed] = useState<FeedData>(() =>
    feedDataFrom(fromFeedCatalogPayload(initial), false),
  );
  const feedRef = useRef(feed);
  feedRef.current = feed;

  // Target first, then the episode after it, in the order the page chose.
  const [items, setItems] = useState<ContentItem[]>(() => {
    const playable = new Map(feed.ordered.map((item) => [item.id, item]));
    return initial.items.flatMap((entry) => {
      const item = playable.get(entry.id);
      return item ? [item] : [];
    });
  });
  const [index, setIndex] = useState(0);
  const [pageReady, setPageReady] = useState(false);

  const [muted, setMuted] = useState(true);
  const [captionsOn, setCaptionsOn] = useState(false);
  const [likedIds, setLikedIds] = useState<Set<string>>(() => new Set());
  const [followingIds, setFollowingIds] = useState<Set<string>>(() => new Set());
  const [progressStore] = useState(createProgressStore);
  const [seekToMs, setSeekToMs] = useState<number | null>(null);
  const [autoplayBlocked, setAutoplayBlocked] = useState(false);
  const [userStartedPlayback, setUserStartedPlayback] = useState(false);
  const [intentOpen, setIntentOpen] = useState(false);
  const [seriesEnded, setSeriesEnded] = useState<SeriesEndKind | null>(null);
  const [resumeOffer, setResumeOffer] = useState<ResumeLanding | null>(null);
  /** The active episode failed; the feed moves on after ERROR_SKIP_DELAY_MS (PB-5). */
  const [playbackFailure, setPlaybackFailure] = useState<string | null>(null);

  const resumeStore = useMemo(() => createLocalStorageResumeStore(), []);
  const progressThrottle = useMemo(() => createWatchProgressThrottle(5_000), []);
  const lastResumeRef = useRef<ResumeSnapshot | null>(null);
  const firstPlayMarked = useRef(false);
  const firstAttemptMarked = useRef(false);
  const openedTracked = useRef(false);
  const deepLinkTracked = useRef(false);
  const contentOpenTracked = useRef<string | null>(null);
  const lastContinueKey = useRef<string | null>(null);
  const sharePlayTracked = useRef(false);
  const transitionRef = useRef<PendingTransition | null>(null);
  /** Autoplay was refused at least once before the first play (MP-2). */
  const autoplayBlockedBeforeFirstPlay = useRef(false);
  /** performance.now() of the play-gate tap, if the viewer needed one. */
  const gateTapAt = useRef<number | null>(null);
  /** The episode a returning viewer landed on. */
  const resumeLandingId = useRef<string | null>(null);
  /** Series already reported complete for an episode, once each. */
  const seriesCompleteSent = useRef<Set<string>>(new Set());
  /** A chip reordered the feed: a late recommendation must not overwrite it (R1). */
  const userReorderedRef = useRef(false);
  const indexRef = useRef(index);
  indexRef.current = index;
  const itemsRef = useRef(items);
  itemsRef.current = items;
  const mountedRef = useRef(true);
  const cancelIdleRef = useRef<(() => void) | null>(null);
  const perf = useMemo(() => createWebPerfTiming(), []);
  const playToggleRef = useRef<() => void>(() => undefined);
  const [diagOpen, setDiagOpen] = useState(false);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
      cancelIdleRef.current?.();
    };
  }, []);

  // Services follow the catalog the feed knows. Cached per catalog so a click
  // right after the catalog arrives never uses the two-item one.
  const recommendationCache = useRef<{ data: FeedData; service: RecommendationService } | null>(
    null,
  );
  const recommendationFor = useCallback(
    (data: FeedData): RecommendationService => {
      if (recommendationCache.current?.data !== data) {
        recommendationCache.current = {
          data,
          service: createRecommendationService({
            catalog: data.ordered,
            feedSource: data.source,
            analytics,
            sessionId,
            store: createLocalStorageTasteStore(),
            enabled: flags.isEnabled("RECOMMENDATION_V0"),
            diversityEnabled: flags.isEnabled("RECOMMENDATION_DIVERSITY_V0"),
            explorationEnabled: flags.isEnabled("RECOMMENDATION_EXPLORATION_V0"),
          }),
        };
      }
      return recommendationCache.current.service;
    },
    [analytics, flags, sessionId],
  );

  const intentCache = useRef<{ data: FeedData; service: CatalogIntentService } | null>(null);
  const intentFor = useCallback(
    (data: FeedData): CatalogIntentService => {
      if (intentCache.current?.data !== data) {
        intentCache.current = {
          data,
          service: createCatalogIntentService({
            analytics,
            sessionId,
            catalog: data.ordered,
            nlEnabled: flags.isEnabled("INTENT_NL_V0"),
          }),
        };
      }
      return intentCache.current.service;
    },
    [analytics, flags, sessionId],
  );

  /** The full catalog, fetched once (retried after a failure). Null if unreachable. */
  const catalogPromise = useRef<Promise<FeedData | null> | null>(null);
  const loadCatalog = useCallback((): Promise<FeedData | null> => {
    if (feedRef.current.complete) return Promise.resolve(feedRef.current);
    catalogPromise.current ??= fetch(catalogUrl)
      .then((response) => {
        if (!response.ok) throw new Error(`catalog answered ${response.status}`);
        return response.json() as Promise<unknown>;
      })
      .then((raw) => {
        const data = feedDataFrom(fromFeedCatalogPayload(raw), true);
        feedRef.current = data;
        if (mountedRef.current) setFeed(data);
        return data;
      })
      .catch(() => {
        // The first-frame items keep playing; the next trigger tries again.
        catalogPromise.current = null;
        return null;
      });
    return catalogPromise.current;
  }, [catalogUrl]);

  /**
   * Builds the feed page: full catalog, then the recommended order after the
   * slides the viewer already has. Scheduled after first play, when the main
   * thread is idle — never inside the first-play window (speed-6).
   */
  const pagePromise = useRef<Promise<void> | null>(null);
  const ensureFeedPage = useCallback((): Promise<void> => {
    pagePromise.current ??= (async () => {
      const data = await loadCatalog();
      if (!data) {
        pagePromise.current = null;
        return;
      }
      try {
        const activeItem = itemsRef.current[indexRef.current] ?? data.ordered[0] ?? null;
        const result = await recommendationFor(data).getOrderedItems({
          sessionId,
          language: "en",
          limit: 40,
          seed: hashSeed(sessionId),
          now: Date.now(),
          excludeContentIds: activeItem ? [activeItem.id] : [],
          activeContentId: activeItem?.id ?? null,
          activeSeriesId: activeItem?.seriesId ?? null,
          diversityEnabled: true,
          explorationEnabled: true,
        });
        const { items: ranked } = materializeFeedItems(result, data.ordered);
        // A chip chosen meanwhile is what the viewer asked for: keep it (R1).
        if (mountedRef.current && ranked.length > 0 && !userReorderedRef.current) {
          setItems((prev) => applyRecommendedPage(prev, indexRef.current, ranked));
        }
      } catch {
        // Editorial order stays — recommendation must never break feed.
      }
      if (mountedRef.current) setPageReady(true);
    })();
    return pagePromise.current;
  }, [loadCatalog, recommendationFor, sessionId]);

  const scheduleFeedPage = useCallback(() => {
    if (pagePromise.current || cancelIdleRef.current) return;
    cancelIdleRef.current = whenIdle(() => {
      cancelIdleRef.current = null;
      void ensureFeedPage();
    });
  }, [ensureFeedPage]);

  // Nothing played after a long while: build the page anyway so swiping has
  // somewhere to go.
  useEffect(() => {
    const timer = window.setTimeout(scheduleFeedPage, CATALOG_FALLBACK_DELAY_MS);
    return () => window.clearTimeout(timer);
  }, [scheduleFeedPage]);

  // A catalog fetch that failed offline is tried again when the network is
  // back, so swiping does not stop at the first-frame slides.
  useEffect(() => {
    const onOnline = () => {
      if (firstPlayMarked.current) scheduleFeedPage();
    };
    window.addEventListener("online", onOnline);
    return () => window.removeEventListener("online", onOnline);
  }, [scheduleFeedPage]);

  // Grow the page near its end, from catalog order. Before the page exists,
  // only reaching the last listed slide builds it early.
  useEffect(() => {
    if (!pageReady) {
      if (index >= items.length - 1) void ensureFeedPage();
      return;
    }
    if (!needsExtension(items.length, index)) return;
    setItems((prev) => extendFeedPage(prev, feed.ordered));
  }, [ensureFeedPage, feed.ordered, index, items.length, pageReady]);

  useEffect(() => {
    perf.mark("app_shell_ready");
    patchLaunchDiagnostics({
      pageStartTs: perf.get("page_start"),
      anonymousUserId,
      sessionId,
    });
    if (!openedTracked.current) {
      openedTracked.current = true;
      analytics.track("page_view", {
        session_id: sessionId,
        route: typeof window !== "undefined" ? window.location.pathname : "/",
      });
    }
    if (isDiagEnabled()) setDiagOpen(true);
  }, [analytics, anonymousUserId, perf, sessionId]);

  useEffect(() => {
    const acquisition = captureAcquisitionFromLocation();
    if (!initialContentId || deepLinkTracked.current) return;
    deepLinkTracked.current = true;
    const item = feedRef.current.ordered.find((entry) => entry.id === initialContentId);
    analytics.track("share_landing", {
      route:
        deepLinkRoute ??
        (typeof window !== "undefined" ? window.location.pathname : null),
      series_id: item?.seriesId ?? null,
      episode_id: item?.episodeId ?? null,
      content_id: item?.id ?? null,
      referrer: acquisition.referrer,
      utm_source: acquisition.utmSource,
      share_id: acquisition.shareId,
    });
    if (item) {
      analytics.track("content_open", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        episode_number: item.episodeNumber,
        episode_count: episodeCountOf(feedRef.current.catalog, item),
        source: acquisition.shareId || acquisition.utmSource ? "share" : "deep_link",
      });
      contentOpenTracked.current = item.id;
      patchLaunchDiagnostics({
        contentOpenTs: Date.now(),
        contentId: item.id,
        seriesId: item.seriesId,
        episodeId: item.episodeId,
      });
    }
  }, [analytics, deepLinkRoute, initialContentId]);

  // Resume from localStorage (non-blocking). Sound always starts off: a saved
  // unmuted preference would make the browser refuse autoplay (PB-3).
  useEffect(() => {
    let cancelled = false;
    void (async () => {
      if (initialContentId) {
        // A shared link resumes only its own series, and never touches the
        // resume points of the others (VIR-2).
        const target = feedRef.current.ordered.find((item) => item.id === initialContentId);
        if (!target) return;
        const saved = await resumeStore.loadForSeries(target.seriesId);
        if (cancelled || !saved) return;
        lastResumeRef.current = saved;
        setCaptionsOn(saved.captionsOn);
        if (saved.contentId === initialContentId && isResumable(saved)) {
          resumeLandingId.current = saved.contentId;
          setResumeOffer({ contentId: saved.contentId, positionMs: saved.positionMs, reason: "resume" });
          patchLaunchDiagnostics({ resumePositionMs: saved.positionMs });
        }
        return;
      }

      const snapshot = await resumeStore.load();
      if (cancelled || !snapshot) return;
      lastResumeRef.current = snapshot;
      setCaptionsOn(snapshot.captionsOn);

      const nextEpisodeIn = (data: FeedData) => (contentId: string) => {
        const saved = data.ordered.find((item) => item.id === contentId);
        return saved ? (data.source.getNextEpisode(saved)?.id ?? null) : null;
      };
      let data = feedRef.current;
      let landing = resumeLanding(snapshot, nextEpisodeIn(data));
      // The first-frame catalog may know neither the saved episode nor the
      // one after it (VIR-1): the full catalog decides.
      const needsCatalog =
        !data.complete &&
        (landing === null
          ? isNearEnd(snapshot)
          : !data.ordered.some((item) => item.id === landing?.contentId));
      if (needsCatalog) {
        const full = await loadCatalog();
        if (cancelled || !full) return;
        data = full;
        landing = resumeLanding(snapshot, nextEpisodeIn(full));
      }
      // Nothing to continue, or the viewer already moved on.
      if (!landing || indexRef.current !== 0) return;
      const target = landing;

      const listed = itemsRef.current.findIndex((item) => item.id === target.contentId);
      if (listed >= 0) {
        setIndex(listed);
      } else {
        // The page holds only the first frame: the episode comes from the
        // catalog and opens a page of its own.
        const landed = data.ordered.find((item) => item.id === target.contentId);
        if (!landed) return;
        setItems((prev) => pageStartingAt(data.source, landed, prev));
        setIndex(0);
      }
      resumeLandingId.current = target.contentId;
      setResumeOffer(target);
      patchLaunchDiagnostics({ resumePositionMs: target.positionMs });
    })();
    return () => {
      cancelled = true;
    };
  }, [initialContentId, loadCatalog, resumeStore]);

  const current = items[index] ?? null;
  const nextItem = items[index + 1] ?? null;
  const prefetchIds = useMemo(
    () => (items.length > 0 ? getPrefetchIds(items, index) : new Set<string>()),
    [items, index],
  );

  // Warm the next episode's poster. Its first seconds of video are warmed by
  // the player itself (planHlsLoad), never the whole episode.
  useEffect(() => {
    if (!nextItem || typeof document === "undefined") return;
    const posterHref = nextItem.playback.posterReference || nextItem.thumbnailUrl;
    const links: HTMLLinkElement[] = [];

    const add = (rel: string, as: string, href: string, type?: string) => {
      const existing = document.head.querySelector(`link[data-flow-prefetch="${href}"]`);
      if (existing) return;
      const link = document.createElement("link");
      link.rel = rel;
      link.as = as;
      link.href = href;
      link.dataset.flowPrefetch = href;
      if (type) link.type = type;
      document.head.appendChild(link);
      links.push(link);
    };

    add("preload", "image", posterHref);

    return () => {
      for (const link of links) link.remove();
    };
  }, [nextItem]);

  // Open first feed item (non-share) once.
  useEffect(() => {
    if (!current || initialContentId) return;
    if (contentOpenTracked.current === current.id) return;
    contentOpenTracked.current = current.id;
    analytics.track("content_open", {
      content_id: current.id,
      series_id: current.seriesId,
      episode_id: current.episodeId,
      episode_number: current.episodeNumber,
      episode_count: episodeCountOf(feedRef.current.catalog, current),
      source: "feed",
    });
    analytics.track("content_impression", {
      content_id: current.id,
      series_id: current.seriesId,
    });
    patchLaunchDiagnostics({
      contentOpenTs: Date.now(),
      contentId: current.id,
      seriesId: current.seriesId,
      episodeId: current.episodeId,
    });
  }, [analytics, current, initialContentId]);

  useEffect(() => {
    if (!current) return;
    patchLaunchDiagnostics({
      contentId: current.id,
      seriesId: current.seriesId,
      episodeId: current.episodeId,
      contentStatus: current.status,
      width: current.playback.width,
      height: current.playback.height,
      aspectRatio: current.playback.aspectRatio,
      captionTracks: current.captions.filter((t) => t.status === "ready").length,
      captionsOn,
      sourceUri: current.videoUrl,
      prefetchIds: [...prefetchIds],
      anonymousUserId,
      sessionId,
      pageStartTs: perf.get("page_start"),
      timeToFirstPlayMs: perf.timeToFirstPlay(),
    });
  }, [anonymousUserId, captionsOn, current, perf, prefetchIds, sessionId]);

  const persistResume = useCallback(
    async (snapshot: ResumeSnapshot) => {
      if (!shouldPersistResume(lastResumeRef.current, snapshot)) return;
      lastResumeRef.current = snapshot;
      await resumeStore.save(snapshot);
    },
    [resumeStore],
  );

  const emitWatchProgress = useCallback(
    (item: ContentItem, positionMs: number, durationMs: number, force = false) => {
      if (force) progressThrottle.forceNext();
      if (
        !force &&
        !progressThrottle.shouldEmit({
          contentId: item.id,
          positionMs,
          durationMs,
        })
      ) {
        return;
      }
      const completion =
        durationMs > 0 ? Math.min(100, (positionMs / durationMs) * 100) : 0;
      analytics.track("watch_progress", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        episode_number: item.episodeNumber,
        episode_count: episodeCountOf(feedRef.current.catalog, item),
        position_ms: Math.round(positionMs),
        duration_ms: Math.round(durationMs),
        completion_percentage: Math.round(completion),
        session_id: sessionId,
        anonymous_user_id: anonymousUserId,
      });
    },
    [analytics, anonymousUserId, progressThrottle, sessionId],
  );

  /** series_complete once per episode, only for the series' last one (MP-7). */
  const trackSeriesComplete = useCallback(
    (item: ContentItem, via: "ended" | "swipe") => {
      if (seriesCompleteSent.current.has(item.id)) return;
      seriesCompleteSent.current.add(item.id);
      analytics.track("series_complete", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_number: item.episodeNumber,
        episode_count: episodeCountOf(feedRef.current.catalog, item),
        via,
      });
    },
    [analytics],
  );

  const handleIndexChange = useCallback(
    (next: number, kind: PendingTransition["kind"] = "swipe", nextItems: ContentItem[] = items) => {
      if (next === index) return;
      const from = items[index];
      if (from) {
        const watched = progressStore.get(from.id);
        emitWatchProgress(from, watched * from.durationMs, from.durationMs, true);
        analytics.track("episode_leave", {
          content_id: from.id,
          series_id: from.seriesId,
          episode_id: from.episodeId,
          completion_percentage: Math.round(watched * 100),
        });
        // Leaving the last episode after watching nearly all of it finishes the series.
        if (
          finishedLastEpisode(
            from.episodeNumber,
            episodeCountOf(feedRef.current.catalog, from),
            watched,
          )
        ) {
          trackSeriesComplete(from, "swipe");
        }
        const watchedPct = watched * 100;
        if (watchedPct > 0 && watchedPct < 40) {
          analytics.track("video_skipped", {
            content_id: from.id,
            completion_percentage: Math.round(watchedPct),
          });
        }
      }
      const to = nextItems[next];
      if (kind === "swipe") {
        analytics.track("feed_swipe", {
          direction: next > index ? "next" : "previous",
          from_content_id: items[index]?.id ?? null,
          to_content_id: to?.id ?? null,
        });
      }
      if (to && contentOpenTracked.current !== to.id) {
        contentOpenTracked.current = to.id;
        analytics.track("content_open", {
          content_id: to.id,
          series_id: to.seriesId,
          episode_id: to.episodeId,
          episode_number: to.episodeNumber,
          episode_count: episodeCountOf(feedRef.current.catalog, to),
          source: kind === "swipe" ? "feed_swipe" : kind,
        });
        analytics.track("content_impression", {
          content_id: to.id,
          series_id: to.seriesId,
        });
      }
      perf.mark("episode_transition_started");
      transitionRef.current = to
        ? { toContentId: to.id, kind, startedAt: performance.now() }
        : null;
      setSeriesEnded(null);
      setResumeOffer(null);
      setSeekToMs(null);
      setAutoplayBlocked(false);
      setPlaybackFailure(null);
      progressThrottle.reset();
      if (nextItems !== items) setItems(nextItems);
      setIndex(next);
    },
    [
      analytics,
      emitWatchProgress,
      index,
      items,
      perf,
      progressStore,
      progressThrottle,
      trackSeriesComplete,
    ],
  );

  // A failed episode stays on screen long enough to read why, then the feed
  // moves on: to the next episode of the series when there is one (PB-5).
  const skipFailedRef = useRef<(contentId: string) => void>(() => undefined);
  skipFailedRef.current = (contentId: string) => {
    const active = items[index];
    if (!active || active.id !== contentId) return;
    analytics.track("playback_error_skip", {
      content_id: active.id,
      series_id: active.seriesId,
      episode_id: active.episodeId,
    });
    const placed = placeNextInSeries(feedRef.current.source, items, index);
    if (placed.kind === "next_in_series") {
      handleIndexChange(placed.nextIndex, "error_skip", placed.items);
      return;
    }
    if (index < items.length - 1) {
      handleIndexChange(index + 1, "error_skip");
      return;
    }
    // Last listed slide: build the page, the extension effect adds slides.
    setPlaybackFailure(null);
    void ensureFeedPage();
  };
  useEffect(() => {
    if (!playbackFailure || current?.id !== playbackFailure) return;
    const timer = window.setTimeout(
      () => skipFailedRef.current(playbackFailure),
      ERROR_SKIP_DELAY_MS,
    );
    return () => window.clearTimeout(timer);
  }, [current?.id, playbackFailure]);

  const handleTimeUpdate = (item: ContentItem, positionMs: number, durationMs: number) => {
    progressStore.set(item.id, durationMs > 0 ? positionMs / durationMs : 0);
    patchLaunchDiagnostics({
      currentTimeMs: positionMs,
      durationMs,
    });
    emitWatchProgress(item, positionMs, durationMs);
    void persistResume({
      contentId: item.id,
      seriesId: item.seriesId,
      episodeId: item.episodeId,
      positionMs,
      durationMs: durationMs || item.durationMs,
      muted,
      captionsOn,
      updatedAt: Date.now(),
      completed: false,
    });
  };

  const handleEnded = (item: ContentItem) => {
    emitWatchProgress(item, item.durationMs, item.durationMs, true);
    analytics.track("episode_complete", {
      content_id: item.id,
      series_id: item.seriesId,
      episode_id: item.episodeId,
      episode_number: item.episodeNumber,
      episode_count: episodeCountOf(feedRef.current.catalog, item),
    });
    void persistResume({
      contentId: item.id,
      seriesId: item.seriesId,
      episodeId: item.episodeId,
      positionMs: item.durationMs,
      durationMs: item.durationMs,
      muted,
      captionsOn,
      updatedAt: Date.now(),
      completed: true,
    });
    void recommendationFor(feedRef.current).recordSignal({
      contentId: item.id,
      seriesId: item.seriesId,
      genres: item.genres,
      tropes: item.tropes,
      language: item.language,
      action: "complete",
      watchDurationMs: item.durationMs,
      completionPercentage: 100,
      now: Date.now(),
    });

    void (async () => {
      let placed = placeNextInSeries(feedRef.current.source, itemsRef.current, indexRef.current);
      if (placed.kind === "series_complete" && !feedRef.current.complete) {
        // The first-frame catalog may not know the next episode yet.
        const data = await loadCatalog();
        if (data) placed = placeNextInSeries(data.source, itemsRef.current, indexRef.current);
      }
      // The viewer moved on meanwhile: nothing to continue.
      if (!mountedRef.current || itemsRef.current[indexRef.current]?.id !== item.id) return;

      if (placed.kind === "next_in_series") {
        const continueKey = `${item.id}->${placed.next.id}`;
        if (lastContinueKey.current !== continueKey) {
          lastContinueKey.current = continueKey;
          analytics.track("series_continue", {
            content_id: item.id,
            series_id: item.seriesId,
            next_content_id: placed.next.id,
            next_episode_id: placed.next.episodeId,
          });
        }
        perf.mark("episode_transition_started");
        transitionRef.current = {
          toContentId: placed.next.id,
          kind: "auto_continue",
          startedAt: performance.now(),
        };
        setSeriesEnded(null);
        setSeekToMs(null);
        setPlaybackFailure(null);
        if (placed.items !== itemsRef.current) setItems(placed.items);
        setIndex(placed.nextIndex);
        return;
      }
      // Only the last episode completes a series; a missing or unready next
      // episode is reported as what it is (MP-7).
      const ending = classifySeriesEnd(
        item.episodeNumber,
        episodeCountOf(feedRef.current.catalog, item),
      );
      if (ending === "series_complete") {
        trackSeriesComplete(item, "ended");
      } else {
        analytics.track("series_unavailable_next", {
          content_id: item.id,
          series_id: item.seriesId,
          episode_number: item.episodeNumber,
          episode_count: episodeCountOf(feedRef.current.catalog, item),
        });
      }
      setSeriesEnded(ending);
    })();
  };

  const handleShare = useCallback(
    async (item: ContentItem) => {
      const origin = typeof window !== "undefined" ? window.location.origin : "";
      const shareId = createShareId();
      const url = buildShareUrl(feedRef.current.catalog, item, origin, {
        utmSource: "share",
        utmMedium: "social",
        shareId,
      });
      if (!url) return;
      analytics.track("share_open", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        share_id: shareId,
      });
      try {
        if (typeof navigator !== "undefined" && typeof navigator.share === "function") {
          await navigator.share({
            title: item.seriesTitle,
            text: item.hook.replace(/\n/g, " "),
            url,
          });
          analytics.track("share_native", {
            content_id: item.id,
            share_id: shareId,
          });
          return;
        }
      } catch {
        // fall through to clipboard
      }
      try {
        await navigator.clipboard.writeText(url);
        analytics.track("share_copy", {
          content_id: item.id,
          share_id: shareId,
        });
      } catch {
        // share best-effort
      }
    },
    [analytics],
  );

  const handleIntentChip = useCallback(
    async (chipId: IntentChipId) => {
      const tapped = itemsRef.current[indexRef.current];
      const data = (await loadCatalog()) ?? feedRef.current;
      const resolution = await intentFor(data).resolveChip(chipId, {
        contentId: tapped?.id ?? null,
        seriesId: tapped?.seriesId ?? null,
        genres: tapped?.genres ?? [],
        tropes: tapped?.tropes ?? [],
      });
      setIntentOpen(false);

      if (resolution.candidates.length === 0) return;

      const byId = new Map(data.ordered.map((item) => [item.id, item]));
      const intentItems = resolution.candidates
        .map((candidate) => byId.get(candidate.contentId))
        .filter((entry): entry is ContentItem => Boolean(entry));

      // The fetch can take seconds: the page is built around the episode on
      // screen now, not the one on screen when the chip was tapped (R2).
      const headIndex = indexRef.current;
      const head = itemsRef.current[headIndex];
      if (!head) return;
      userReorderedRef.current = true;
      setItems((prev) => applyIntentPage(prev, head.id, intentItems));
      setIndex(0);
    },
    [intentFor, loadCatalog],
  );

  const showGate = shouldShowPlayGate(autoplayBlocked, userStartedPlayback);

  const handlePlayGate = () => {
    if (!firstPlayMarked.current && gateTapAt.current === null) {
      gateTapAt.current = performance.now();
    }
    setUserStartedPlayback(true);
    setAutoplayBlocked(false);
    analytics.track("first_play_attempted", {
      session_id: sessionId,
      content_id: items[index]?.id ?? null,
      source: "play_gate",
    });
    const video = document.querySelector<HTMLVideoElement>(
      `[data-content-id="${items[index]?.id ?? ""}"] video`,
    );
    if (video) {
      void video.play().catch(() => undefined);
    }
  };

  playToggleRef.current = () => {
    const video = document.querySelector<HTMLVideoElement>(
      `[data-content-id="${items[index]?.id ?? ""}"] video`,
    );
    if (!video) return;
    if (video.paused) {
      void video.play().catch(() => setAutoplayBlocked(true));
    } else {
      video.pause();
    }
  };

  const handlerImpl: FeedItemHandlers = {
    onToggleMute: () => setMuted((value) => !value),
    onUnmute: () => setMuted(false),
    onToggleCaptions: () => {
      setCaptionsOn((value) => {
        const next = !value;
        analytics.track("caption_toggled", {
          session_id: sessionId,
          captions_on: next,
          content_id: current?.id ?? null,
        });
        return next;
      });
    },
    onTogglePlayPause: () => playToggleRef.current(),
    onPlayGate: handlePlayGate,
    onLike: (item) => {
      setLikedIds((prev) => {
        const next = new Set(prev);
        if (next.has(item.id)) next.delete(item.id);
        else next.add(item.id);
        return next;
      });
      analytics.track("like", {
        content_id: item.id,
        series_id: item.seriesId,
      });
      void recommendationFor(feedRef.current).recordSignal({
        contentId: item.id,
        seriesId: item.seriesId,
        genres: item.genres,
        tropes: item.tropes,
        language: item.language,
        action: "like",
        watchDurationMs: 0,
        completionPercentage: 0,
        now: Date.now(),
      });
    },
    onFollow: (item) => {
      setFollowingIds((prev) => {
        const next = new Set(prev);
        if (next.has(item.seriesId)) next.delete(item.seriesId);
        else next.add(item.seriesId);
        return next;
      });
      analytics.track("follow", {
        content_id: item.id,
        series_id: item.seriesId,
      });
      void recommendationFor(feedRef.current).recordSignal({
        contentId: item.id,
        seriesId: item.seriesId,
        genres: item.genres,
        tropes: item.tropes,
        language: item.language,
        action: "follow",
        watchDurationMs: 0,
        completionPercentage: 0,
        now: Date.now(),
      });
    },
    onShare: (item) => {
      void handleShare(item);
    },
    onTune: () => {
      if (!flags.isEnabled("INTENT_LAYER")) return;
      analytics.track("intent_open", { session_id: sessionId });
      setIntentOpen(true);
    },
    onMetadataReady: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("content_metadata_ready");
    },
    onPosterVisible: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("poster_visible");
    },
    onLoadStart: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("video_load_started");
    },
    onCanPlay: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("video_can_play");
      analytics.track("video_ready", {
        session_id: sessionId,
        content_id: item.id,
      });
    },
    onTimeUpdate: handleTimeUpdate,
    onEnded: handleEnded,
    onError: (item, code, reason) => {
      analytics.track("playback_error", {
        session_id: sessionId,
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        error_code: code,
        reason,
      });
      // Only the episode on screen moves the feed; a neighbour never does
      // (PB-4, R3). The skip waits until the error has been read (PB-5).
      if (item.id !== current?.id) return;
      scheduleFeedPage();
      setPlaybackFailure(item.id);
    },
    onRetry: (item) => {
      analytics.track("playback_retry", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
      });
      setPlaybackFailure(null);
    },
    onPlayAttempt: (item) => {
      patchLaunchDiagnostics({
        autoplayAttempted: true,
        playAttemptTs: Date.now(),
        playerState: "loading",
      });
      if (firstAttemptMarked.current) return;
      firstAttemptMarked.current = true;
      analytics.track("first_play_attempted", {
        content_id: item.id,
        source: "autoplay",
      });
    },
    onPlay: () => {
      // Playback requested and unpaused; no frame yet, so no speed metric here.
      setAutoplayBlocked(false);
      setUserStartedPlayback(true);
    },
    onMutedFallback: (item) => {
      setMuted(true);
      analytics.track("autoplay_muted_fallback", {
        content_id: item.id,
        series_id: item.seriesId,
      });
    },
    onSeekApplied: (item) => {
      if (item.id !== current?.id) return;
      // Applied once: a later canplay must never replay it (PB-2).
      setSeekToMs(null);
    },
    onPlaying: (item, info) => {
      if (item.id !== current?.id) return;
      setAutoplayBlocked(false);
      setUserStartedPlayback(true);
      patchLaunchDiagnostics({
        playerState: "playing",
        autoplayBlocked: false,
        contentId: item.id,
        seriesId: item.seriesId,
        episodeId: item.episodeId,
        sourceUri: item.videoUrl,
      });
      if (info.firstFrame) perf.mark("episode_first_frame_played");
      if (info.firstFrame && !firstPlayMarked.current) {
        firstPlayMarked.current = true;
        perf.mark("video_play_started");
        perf.mark("first_meaningful_play");
        const ttfp = perf.timeToFirstPlay();
        const startMode = firstPlayStartMode({
          gateTapped: gateTapAt.current !== null,
          resumeLandingId: resumeLandingId.current,
          contentId: item.id,
        });
        patchLaunchDiagnostics({
          firstMeaningfulPlayTs: perf.get("first_meaningful_play"),
          timeToFirstPlayMs: ttfp,
        });
        analytics.track("first_meaningful_play", {
          content_id: item.id,
          series_id: item.seriesId,
          episode_id: item.episodeId,
          time_to_first_play: ttfp,
          // docs/standard.md §3 judges time_to_first_play on start_mode = autoplay.
          start_mode: startMode,
          autoplay_blocked: autoplayBlockedBeforeFirstPlay.current,
          gate_tap_to_play_ms:
            gateTapAt.current === null
              ? null
              : Math.round(performance.now() - gateTapAt.current),
          frame_source: info.frameSource,
          page_start_ts: perf.get("page_start"),
          video_load_started_ts: perf.get("video_load_started"),
          video_can_play_ts: perf.get("video_can_play"),
          first_meaningful_play_ts: perf.get("first_meaningful_play"),
        });
        const acquisition = loadAcquisitionContext();
        if (
          !sharePlayTracked.current &&
          (acquisition?.shareId || acquisition?.utmSource === "share")
        ) {
          sharePlayTracked.current = true;
          analytics.track("share_play", {
            content_id: item.id,
            series_id: item.seriesId,
            share_id: acquisition.shareId,
            utm_source: acquisition.utmSource,
          });
        }
        // The episode is playing: the rest of the feed can now be prepared.
        scheduleFeedPage();
      }
      // Swipe latency ends at the first real frame of the episode swiped to,
      // measured on one clock (MP-1).
      const transition = transitionRef.current;
      const transitionMs =
        info.firstFrame && transition?.toContentId === item.id
          ? Math.round(performance.now() - transition.startedAt)
          : null;
      if (info.firstFrame && transition?.toContentId === item.id) transitionRef.current = null;
      analytics.track("play", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        first_frame: info.firstFrame,
        frame_source: info.frameSource,
        swipe_to_play_ms: transition?.kind === "swipe" ? transitionMs : null,
        transition_kind: transitionMs === null ? null : (transition?.kind ?? null),
        transition_to_play_ms: transitionMs,
      });
    },
    onPause: () => {
      patchLaunchDiagnostics({ playerState: "paused" });
      analytics.track("pause", {
        content_id: current?.id ?? null,
      });
    },
    onBufferingStart: (item) => {
      patchLaunchDiagnostics({ playerState: "buffering" });
      analytics.track("buffer_start", {
        content_id: item.id,
      });
    },
    onBufferingEnd: (item) => {
      patchLaunchDiagnostics({ playerState: "playing" });
      analytics.track("buffer_end", {
        content_id: item.id,
      });
    },
    onAutoplayBlocked: () => {
      // Waiting for a tap: the main thread is free for the feed page.
      scheduleFeedPage();
      if (!firstPlayMarked.current) autoplayBlockedBeforeFirstPlay.current = true;
      if (!userStartedPlayback) {
        setAutoplayBlocked(true);
        patchLaunchDiagnostics({
          autoplayBlocked: true,
          playerState: "autoplay_blocked",
        });
      }
    },
  };
  const latestHandlers = useRef(handlerImpl);
  latestHandlers.current = handlerImpl;
  const [handlers] = useState(() => createStableHandlers(latestHandlers));

  if (items.length === 0) {
    return (
      <main className={styles.root}>
        <FeedStage>
          <p className={styles.empty}>Finding something great…</p>
        </FeedStage>
      </main>
    );
  }

  return (
    <main className={styles.root}>
      <FeedStage>
        <FeedScroller
          items={items}
          index={index}
          onIndexChange={handleIndexChange}
          muted={muted}
          captionsOn={captionsOn}
          likedIds={likedIds}
          followingIds={followingIds}
          seekToMs={seekToMs}
          showPlayGate={showGate}
          prefetchIds={prefetchIds}
          locale={locale}
          progressStore={progressStore}
          handlers={handlers}
        />

        {resumeOffer && current?.id === resumeOffer.contentId ? (
          <ContinueStrip
            seriesTitle={current.seriesTitle}
            episodeLabel={`Episode ${current.episodeNumber}`}
            label={resumeOffer.reason === "next_episode" ? "Up next" : "Continue story"}
            onContinue={() => {
              // Seeks right away when the episode is loaded (PB-2).
              if (resumeOffer.positionMs > 0) setSeekToMs(resumeOffer.positionMs);
              setResumeOffer(null);
              analytics.track("episode_resume_started", {
                session_id: sessionId,
                content_id: resumeOffer.contentId,
                position_ms: resumeOffer.positionMs,
                reason: resumeOffer.reason,
              });
              const resumeIndex = items.findIndex(
                (item) => item.id === resumeOffer.contentId,
              );
              if (resumeIndex >= 0 && resumeIndex !== index) setIndex(resumeIndex);
            }}
          />
        ) : null}

        {seriesEnded && current ? (
          <SeriesEnd
            seriesTitle={current.seriesTitle}
            kind={seriesEnded}
            onDismiss={() => {
              setSeriesEnded(null);
              if (index < items.length - 1) {
                handleIndexChange(index + 1);
              }
            }}
          />
        ) : null}

        <IntentSheet
          open={intentOpen}
          onClose={() => setIntentOpen(false)}
          onSelect={(chipId) => {
            analytics.track("intent_select", { chip_id: chipId });
            void handleIntentChip(chipId);
          }}
        />

        {diagOpen ? (
          <LaunchDiagPanel
            onClose={() => setDiagOpen(false)}
            transport={getAnalyticsTransport()}
          />
        ) : null}
      </FeedStage>
    </main>
  );
}
