"use client";

import {
  applyIntentPage,
  applyRecommendedPage,
  classifySeriesEnd,
  createCatalogIntentService,
  createDeterministicFeedSource,
  createLocalStorageResumeStore,
  createLocalStorageTasteStore,
  createRecommendationService,
  createWatchProgressThrottle,
  createWebPerfTiming,
  extendFeedPage,
  finishedLastEpisode,
  fromFeedCatalogPayload,
  getPrefetchIds,
  isNearEnd,
  isResumable,
  keepsFinishedEpisode,
  materializeFeedItems,
  needsExtension,
  pageStartingAt,
  placeNextInSeries,
  resumeLanding,
  shouldPersistResume,
  type CatalogIntentService,
  type ContentItem,
  type FeedCatalog,
  type FeedCatalogPayload,
  type FeedSource,
  type IntentChipId,
  type RecommendationService,
  type ResumeLanding,
  type ResumeSnapshot,
  type SeriesEndKind,
} from "@project-flow/feed-domain";
import { createLocalFeatureFlags } from "@project-flow/shared";
import {
  useCallback,
  useEffect,
  useMemo,
  useRef,
  useState,
  type ReactElement,
} from "react";

import {
  getAnalyticsClient,
  getAnalyticsTransport,
  getAnonymousUserId,
  getSessionId,
} from "@/lib/analytics";
import {
  captureAcquisitionFromLocation,
  createShareId,
  isDiagEnabled,
  loadAcquisitionContext,
} from "@/lib/session";
import { shareMessage } from "@/lib/siteMetadata";
import { shareOrigin } from "@/lib/siteUrl";

import { LaunchDiagPanel } from "@/features/diagnostics/LaunchDiagPanel";
import { patchLaunchDiagnostics } from "@/features/diagnostics/launchDiagnostics";
import { InstallOffer } from "@/features/platform/InstallOffer";
import { displayMode } from "@/features/platform/installRules";
import { useInstallOffer } from "@/features/platform/useInstallOffer";

import { episodeAnnouncement, intentConfirmation, shouldAnnounceEpisode } from "./a11y";
import { FREE_FOREVER_LINE } from "@/lib/promise";

import type { RetentionRuntime, RetentionView } from "@/features/retention/RetentionLayer";

import { ContinueStrip, UpNextLabel } from "./ContinueStrip";
import type { FeedItemHandlers } from "./FeedItemView";
import { FeedScroller } from "./FeedScroller";
import { FeedStage } from "./FeedStage";
import { NoticePill, type Notice } from "./NoticePill";
import {
  CAPTIONS_PREFERENCE_KEY,
  SOUND_CUE_SESSION_KEY,
  SOUND_CUE_VISIBLE_MS,
  effectiveCaptions,
  episodePosition,
  migratedCaptionChoice,
  nextCaptionChoice,
  parseCaptionChoice,
  parseShareStartMs,
  pickNextStory,
  placeStory,
  serializeCaptionChoice,
  shareStartSeconds,
  shouldHoldNotice,
  shouldShowSoundCue,
  storyShareTarget,
  type CaptionChoice,
} from "./storyThread";
import {
  ERROR_SKIP_DELAY_MS,
  buildShareUrl,
  failureHoldFor,
  feedExhausted,
  firstPlayStartMode,
  shouldShowPlayGate,
  type PlaybackFailure,
} from "./feedLogic";
import { createProgressStore, createStableHandlers } from "./progressStore";
import styles from "./feed.module.css";

/** Static file generated by app/catalog/feed.json/route.ts. */
export const FEED_CATALOG_URL = "/catalog/feed.json";
/**
 * Build the page even when nothing has played yet. Long on purpose: measured
 * on a throttled phone (1.6 Mbps, 4x CPU), first play takes about 9 s, and a
 * 4 s fallback parsed the catalog right in the middle of it. A refused
 * autoplay or a playback error schedules the page immediately instead.
 */
const CATALOG_FALLBACK_DELAY_MS = 20_000;

/**
 * "Free forever. No coins, no unlocks." is said once on this device, at the
 * first swipe — the moment the viewer chooses a second episode, which is
 * where the apps they know start asking for money. Never at the cold open
 * (nothing may stand between a link and a picture), never twice.
 */
const FREE_FOREVER_KEY = "project-flow.free-forever.v1";

/**
 * The lazily loaded retention chunk (features/retention/RetentionLayer.tsx):
 * follow, like, what was watched and the news line, fetched after the first
 * frame. Only its types are named here, which cost the feed nothing.
 */
type RetentionModule = typeof import("@/features/retention/RetentionLayer");
type LoadedRetention = { mod: RetentionModule; runtime: RetentionRuntime };
/**
 * Surfaces that are never on screen before a first frame — the end of a
 * series, the Tune sheet — are not loaded before one either: they come at the
 * retention chunk's idle moment, or at once when asked for sooner. Together
 * with the retention chunk they keep the feed's first-load JavaScript from
 * growing with this batch (docs/decisions.md, batch 8).
 */
const loadSeriesEnd = () => import("./SeriesEnd");
const loadIntentSheet = () => import("./IntentSheet");

/** A module fetched late: null until it is in, and one fetch however often asked. */
function useLateModule<T>(load: () => Promise<T>): { module: T | null; ensure: () => void } {
  const [module, setModule] = useState<T | null>(null);
  const promise = useRef<Promise<void> | null>(null);
  const alive = useRef(true);
  useEffect(() => {
    alive.current = true;
    return () => {
      alive.current = false;
    };
  }, []);
  const ensure = useCallback(() => {
    promise.current ??= load()
      .then((loaded) => {
        if (alive.current) setModule(() => loaded);
      })
      .catch(() => {
        // Tried again at the next ask; the feed never waits on it.
        promise.current = null;
      });
  }, [load]);
  return { module, ensure };
}
const NO_RETENTION: RetentionView = { following: new Set(), liked: new Set() };

/** The rail answers a tap at once, before the device has recorded it. */
function flipped(set: ReadonlySet<string>, id: string): Set<string> {
  const next = new Set(set);
  if (next.has(id)) next.delete(id);
  else next.add(id);
  return next;
}

type FeedAppProps = {
  /** Target episode and the one after it, inlined in the page. */
  initial: FeedCatalogPayload;
  /** Deep-link starting content (watch route). */
  initialContentId?: string | undefined;
  deepLinkRoute?: string | undefined;
  catalogUrl?: string;
};

/** The catalog the feed currently knows: the first-frame items, then the full one. */
type FeedData = {
  catalog: FeedCatalog;
  source: FeedSource;
  ordered: ContentItem[];
  complete: boolean;
};

function feedDataFrom(catalog: FeedCatalog, complete: boolean): FeedData {
  const source = createDeterministicFeedSource(catalog);
  return {
    catalog: source.loadCatalog(),
    source,
    ordered: source.getOrderedItems(),
    complete,
  };
}

/** Runs when the main thread is free, so work never competes with first play. */
function whenIdle(callback: () => void): () => void {
  if (typeof window.requestIdleCallback === "function") {
    const handle = window.requestIdleCallback(callback, { timeout: 2_000 });
    return () => window.cancelIdleCallback(handle);
  }
  const timer = window.setTimeout(callback, 200);
  return () => window.clearTimeout(timer);
}

/** How long each notice stays; the sound cue also leaves at the first tap. */
const NOTICE_MS: Record<Notice["kind"], number> = {
  sound: SOUND_CUE_VISIBLE_MS,
  share_copied: 1_800,
  // Long enough to select the link by hand.
  share_failed: 6_000,
  intent: 2_400,
  // One sentence, read once, while an episode keeps playing behind it.
  free_forever: 4_500,
};
/** A held notice checks again this often whether the viewer is done with it. */
const NOTICE_HOLD_RECHECK_MS = 1_000;
/** The "Next episode" label of a returning viewer fades after this. */
const UP_NEXT_LABEL_MS = 4_000;

function readStored(storage: "local" | "session", key: string): string | null {
  try {
    return (storage === "local" ? window.localStorage : window.sessionStorage).getItem(
      key,
    );
  } catch {
    return null;
  }
}

function writeStored(storage: "local" | "session", key: string, value: string): void {
  try {
    (storage === "local" ? window.localStorage : window.sessionStorage).setItem(
      key,
      value,
    );
  } catch {
    // private mode or blocked storage: the choice lasts for this page only
  }
}

/** A move to another episode whose first frame is still to come (MP-1). */
type PendingTransition = {
  toContentId: string;
  kind: "swipe" | "auto_continue" | "error_skip" | "next_story";
  /** performance.now() when the move started. */
  startedAt: number;
};

function episodeCountOf(catalog: FeedCatalog, item: ContentItem): number | null {
  return (
    catalog.series.find((series) => series.id === item.seriesId)?.totalEpisodes ?? null
  );
}

function seriesSlugOf(catalog: FeedCatalog, seriesId: string): string | null {
  return catalog.series.find((series) => series.id === seriesId)?.seriesSlug ?? null;
}

function hashSeed(input: string): number {
  let h = 2166136261;
  for (let i = 0; i < input.length; i += 1) {
    h ^= input.charCodeAt(i);
    h = Math.imul(h, 16777619);
  }
  return h >>> 0;
}

export function FeedApp({
  initial,
  initialContentId,
  deepLinkRoute,
  catalogUrl = FEED_CATALOG_URL,
}: FeedAppProps): ReactElement {
  const analytics = useMemo(() => getAnalyticsClient(), []);
  const sessionId = useMemo(() => getSessionId(), []);
  const anonymousUserId = useMemo(() => getAnonymousUserId(), []);
  const locale = typeof navigator !== "undefined" ? navigator.language : "en";
  const flags = useMemo(
    () =>
      createLocalFeatureFlags({
        FEED_V0: true,
        RECOMMENDATION_V0: true,
        RECOMMENDATION_DIVERSITY_V0: true,
        RECOMMENDATION_EXPLORATION_V0: true,
        INTENT_LAYER: true,
        INTENT_CHIPS_V0: true,
      }),
    [],
  );

  const [feed, setFeed] = useState<FeedData>(() =>
    feedDataFrom(fromFeedCatalogPayload(initial), false),
  );
  const feedRef = useRef(feed);
  feedRef.current = feed;

  // Target first, then the episode after it, in the order the page chose.
  const [items, setItems] = useState<ContentItem[]>(() => {
    const playable = new Map(feed.ordered.map((item) => [item.id, item]));
    return initial.items.flatMap((entry) => {
      const item = playable.get(entry.id);
      return item ? [item] : [];
    });
  });
  const [index, setIndex] = useState(0);
  const [pageReady, setPageReady] = useState(false);

  const [muted, setMuted] = useState(true);
  const mutedRef = useRef(muted);
  mutedRef.current = muted;
  /** The viewer's explicit caption choice; null follows the sound (decision 3). */
  const [captionChoice, setCaptionChoice] = useState<CaptionChoice>(null);
  const captionChoiceRef = useRef(captionChoice);
  captionChoiceRef.current = captionChoice;
  const captionsOn = effectiveCaptions(captionChoice, muted, true);
  const [notice, setNotice] = useState<Notice | null>(null);
  const noticeSeq = useRef(0);
  /** The active episode whose first frame is on screen (for the sound cue). */
  const [framedContentId, setFramedContentId] = useState<string | null>(null);
  /** When that first frame came, so a late cue never interrupts (R3A-02). */
  const framedAtRef = useRef<{ contentId: string; at: number } | null>(null);
  const soundCueShown = useRef(false);
  /** The free-forever line was already said on this device (FREE_FOREVER_KEY). */
  const freeForeverShown = useRef(false);
  /** Whether anything owns the screen right now, readable from an event. */
  const cueBlockedRef = useRef(false);
  /** `?t=` of a shared link, applied to the landing episode only (OPP-02). */
  const shareStartMs = useRef<number | null>(null);
  /**
   * Follow and like, kept on this device (retentionState.ts). Empty until the
   * retention chunk is in, which is after the first frame (ensureRetention):
   * the rail drawing its follow state a moment late costs nothing, the first
   * frame paying for it cost 108 ms on a throttled phone.
   */
  const [retention, setRetentionView] = useState<RetentionView>(NO_RETENTION);
  const likedIds = retention.liked;
  const followingIds = retention.following;
  const [retentionLoaded, setRetentionLoaded] = useState<LoadedRetention | null>(null);
  const retentionRef = useRef<LoadedRetention | null>(null);
  const retentionPromise = useRef<Promise<LoadedRetention | null> | null>(null);
  const seriesEnd = useLateModule(loadSeriesEnd);
  const intentSheet = useLateModule(loadIntentSheet);
  const ensureSeriesEnd = seriesEnd.ensure;
  const ensureIntentSheet = intentSheet.ensure;
  /** The "new since you were here" strip is on screen, over the title block. */
  const [newsCovering, setNewsCovering] = useState(false);
  const [progressStore] = useState(createProgressStore);
  const [seekToMs, setSeekToMs] = useState<number | null>(null);
  const [autoplayBlocked, setAutoplayBlocked] = useState(false);
  const [userStartedPlayback, setUserStartedPlayback] = useState(false);
  const [intentOpen, setIntentOpen] = useState(false);
  const [seriesEnded, setSeriesEnded] = useState<SeriesEndKind | null>(null);
  const [resumeOffer, setResumeOffer] = useState<ResumeLanding | null>(null);
  /** The active episode failed; the feed moves on after ERROR_SKIP_DELAY_MS (PB-5). */
  const [playbackFailure, setPlaybackFailure] = useState<PlaybackFailure | null>(null);
  /** Connection failures skipped since an episode last played (CONNECTION_SKIP_LIMIT). */
  const connectionSkipsRef = useRef(0);
  /** A failed last slide waits for the page to grow before skipping. */
  const pendingSkipRef = useRef<string | null>(null);

  const resumeStore = useMemo(() => createLocalStorageResumeStore(), []);
  const progressThrottle = useMemo(() => createWatchProgressThrottle(5_000), []);
  const lastResumeRef = useRef<ResumeSnapshot | null>(null);
  const firstPlayMarked = useRef(false);
  const firstAttemptMarked = useRef(false);
  const openedTracked = useRef(false);
  const deepLinkTracked = useRef(false);
  const contentOpenTracked = useRef<string | null>(null);
  const lastContinueKey = useRef<string | null>(null);
  const sharePlayTracked = useRef(false);
  const transitionRef = useRef<PendingTransition | null>(null);
  /** Autoplay was refused at least once before the first play (MP-2). */
  const autoplayBlockedBeforeFirstPlay = useRef(false);
  /** performance.now() of the play-gate tap, if the viewer needed one. */
  const gateTapAt = useRef<number | null>(null);
  /** The episode a returning viewer landed on. */
  const resumeLandingId = useRef<string | null>(null);
  /** Series already reported complete for an episode, once each. */
  const seriesCompleteSent = useRef<Set<string>>(new Set());
  /** A chip reordered the feed: a late recommendation must not overwrite it (R1). */
  const userReorderedRef = useRef(false);
  const indexRef = useRef(index);
  indexRef.current = index;
  const itemsRef = useRef(items);
  itemsRef.current = items;
  const mountedRef = useRef(true);
  const cancelIdleRef = useRef<(() => void) | null>(null);
  const perf = useMemo(() => createWebPerfTiming(), []);
  const playToggleRef = useRef<() => void>(() => undefined);
  const [diagOpen, setDiagOpen] = useState(false);

  useEffect(() => {
    mountedRef.current = true;
    return () => {
      mountedRef.current = false;
      cancelIdleRef.current?.();
    };
  }, []);

  // Services follow the catalog the feed knows. Cached per catalog so a click
  // right after the catalog arrives never uses the two-item one.
  const recommendationCache = useRef<{
    data: FeedData;
    service: RecommendationService;
  } | null>(null);
  const recommendationFor = useCallback(
    (data: FeedData): RecommendationService => {
      if (recommendationCache.current?.data !== data) {
        recommendationCache.current = {
          data,
          service: createRecommendationService({
            catalog: data.ordered,
            feedSource: data.source,
            analytics,
            sessionId,
            store: createLocalStorageTasteStore(),
            enabled: flags.isEnabled("RECOMMENDATION_V0"),
            diversityEnabled: flags.isEnabled("RECOMMENDATION_DIVERSITY_V0"),
            explorationEnabled: flags.isEnabled("RECOMMENDATION_EXPLORATION_V0"),
          }),
        };
      }
      return recommendationCache.current.service;
    },
    [analytics, flags, sessionId],
  );

  const intentCache = useRef<{ data: FeedData; service: CatalogIntentService } | null>(
    null,
  );
  const intentFor = useCallback(
    (data: FeedData): CatalogIntentService => {
      if (intentCache.current?.data !== data) {
        intentCache.current = {
          data,
          service: createCatalogIntentService({
            analytics,
            sessionId,
            catalog: data.ordered,
            nlEnabled: flags.isEnabled("INTENT_NL_V0"),
          }),
        };
      }
      return intentCache.current.service;
    },
    [analytics, flags, sessionId],
  );

  /** The full catalog, fetched once (retried after a failure). Null if unreachable. */
  const catalogPromise = useRef<Promise<FeedData | null> | null>(null);
  const loadCatalog = useCallback((): Promise<FeedData | null> => {
    if (feedRef.current.complete) return Promise.resolve(feedRef.current);
    catalogPromise.current ??= fetch(catalogUrl)
      .then((response) => {
        if (!response.ok) throw new Error(`catalog answered ${response.status}`);
        return response.json() as Promise<unknown>;
      })
      .then((raw) => {
        const data = feedDataFrom(fromFeedCatalogPayload(raw), true);
        feedRef.current = data;
        if (mountedRef.current) setFeed(data);
        return data;
      })
      .catch(() => {
        // The first-frame items keep playing; the next trigger tries again.
        catalogPromise.current = null;
        return null;
      });
    return catalogPromise.current;
  }, [catalogUrl]);

  /**
   * Builds the feed page: full catalog, then the recommended order after the
   * slides the viewer already has. Scheduled after first play, when the main
   * thread is idle — never inside the first-play window (speed-6).
   */
  const pagePromise = useRef<Promise<void> | null>(null);
  const ensureFeedPage = useCallback((): Promise<void> => {
    pagePromise.current ??= (async () => {
      const data = await loadCatalog();
      if (!data) {
        pagePromise.current = null;
        return;
      }
      try {
        const activeItem = itemsRef.current[indexRef.current] ?? data.ordered[0] ?? null;
        const result = await recommendationFor(data).getOrderedItems({
          sessionId,
          language: "en",
          limit: 40,
          seed: hashSeed(sessionId),
          now: Date.now(),
          excludeContentIds: activeItem ? [activeItem.id] : [],
          activeContentId: activeItem?.id ?? null,
          activeSeriesId: activeItem?.seriesId ?? null,
          diversityEnabled: true,
          explorationEnabled: true,
        });
        const { items: ranked } = materializeFeedItems(result, data.ordered);
        // A chip chosen meanwhile is what the viewer asked for: keep it (R1).
        if (mountedRef.current && ranked.length > 0 && !userReorderedRef.current) {
          setItems((prev) => applyRecommendedPage(prev, indexRef.current, ranked));
        }
      } catch {
        // Editorial order stays — recommendation must never break feed.
      }
      if (mountedRef.current) setPageReady(true);
    })();
    return pagePromise.current;
  }, [loadCatalog, recommendationFor, sessionId]);

  /**
   * The retention chunk (follow, like, what was watched, the news line),
   * fetched once — at scheduleFeedPage's idle moment after the first frame, or
   * at the first tap on Follow or Like if that comes sooner. A failed fetch is
   * tried again at the next trigger; the feed never waits for it.
   */
  const ensureRetention = useCallback((): Promise<LoadedRetention | null> => {
    retentionPromise.current ??= import("@/features/retention/RetentionLayer")
      .then((mod) => {
        const loaded: LoadedRetention = { mod, runtime: mod.createRetentionRuntime() };
        retentionRef.current = loaded;
        if (mountedRef.current) {
          setRetentionLoaded(loaded);
          setRetentionView(mod.viewOf(loaded.runtime.state()));
        }
        return loaded;
      })
      .catch(() => {
        retentionPromise.current = null;
        return null;
      });
    return retentionPromise.current;
  }, []);

  const retentionScheduled = useRef(false);
  const scheduleFeedPage = useCallback(() => {
    // Same moment, same rule as the catalog: after the first frame (or a
    // refused autoplay, an error, the fallback), when the thread is free. On
    // its own guard: the page can already be building from another path.
    if (!retentionScheduled.current) {
      retentionScheduled.current = true;
      whenIdle(() => {
        void ensureRetention();
        ensureSeriesEnd();
        ensureIntentSheet();
      });
    }
    if (pagePromise.current || cancelIdleRef.current) return;
    cancelIdleRef.current = whenIdle(() => {
      cancelIdleRef.current = null;
      void ensureFeedPage();
    });
  }, [ensureFeedPage, ensureIntentSheet, ensureRetention, ensureSeriesEnd]);

  // Asked for before the idle moment: fetched at once.
  useEffect(() => {
    if (seriesEnded) ensureSeriesEnd();
  }, [ensureSeriesEnd, seriesEnded]);
  useEffect(() => {
    if (intentOpen) ensureIntentSheet();
  }, [ensureIntentSheet, intentOpen]);

  // Nothing played after a long while: build the page anyway so swiping has
  // somewhere to go.
  useEffect(() => {
    const timer = window.setTimeout(scheduleFeedPage, CATALOG_FALLBACK_DELAY_MS);
    return () => window.clearTimeout(timer);
  }, [scheduleFeedPage]);

  // A catalog fetch that failed offline is tried again when the network is
  // back, so swiping does not stop at the first-frame slides.
  useEffect(() => {
    const onOnline = () => {
      if (firstPlayMarked.current) scheduleFeedPage();
    };
    window.addEventListener("online", onOnline);
    return () => window.removeEventListener("online", onOnline);
  }, [scheduleFeedPage]);

  // Grow the page near its end, from catalog order. Before the page exists,
  // only reaching the last listed slide builds it early.
  useEffect(() => {
    if (!pageReady) {
      if (index >= items.length - 1) void ensureFeedPage();
      return;
    }
    if (!needsExtension(items.length, index)) return;
    setItems((prev) => extendFeedPage(prev, feed.ordered));
  }, [ensureFeedPage, feed.ordered, index, items.length, pageReady]);

  useEffect(() => {
    perf.mark("app_shell_ready");
    patchLaunchDiagnostics({
      pageStartTs: perf.get("page_start"),
      anonymousUserId,
      sessionId,
    });
    if (!openedTracked.current) {
      openedTracked.current = true;
      analytics.track("page_view", {
        session_id: sessionId,
        route: typeof window !== "undefined" ? window.location.pathname : "/",
        // Browser tab or installed app: how many come back from the home
        // screen is measured here, not guessed from install prompts.
        display_mode:
          typeof window !== "undefined"
            ? displayMode(
                (query) => window.matchMedia(query).matches,
                (window.navigator as Navigator & { standalone?: boolean }).standalone === true,
              )
            : "browser",
      });
    }
    if (isDiagEnabled()) setDiagOpen(true);
  }, [analytics, anonymousUserId, perf, sessionId]);

  useEffect(() => {
    const acquisition = captureAcquisitionFromLocation();
    if (!initialContentId || deepLinkTracked.current) return;
    deepLinkTracked.current = true;
    const item = feedRef.current.ordered.find((entry) => entry.id === initialContentId);
    // A shared moment opens where it was shared (OPP-02). The first play stays
    // an autoplay: the seek is applied before the first frame.
    const startMs = item
      ? parseShareStartMs(window.location.search, item.durationMs)
      : null;
    if (startMs !== null) {
      shareStartMs.current = startMs;
      setSeekToMs(startMs);
    }
    analytics.track("share_landing", {
      start_ms: startMs,
      route:
        deepLinkRoute ??
        (typeof window !== "undefined" ? window.location.pathname : null),
      series_id: item?.seriesId ?? null,
      episode_id: item?.episodeId ?? null,
      content_id: item?.id ?? null,
      referrer: acquisition.referrer,
      utm_source: acquisition.utmSource,
      share_id: acquisition.shareId,
    });
    if (item) {
      analytics.track("content_open", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        episode_number: item.episodeNumber,
        episode_count: episodeCountOf(feedRef.current.catalog, item),
        source: acquisition.shareId || acquisition.utmSource ? "share" : "deep_link",
      });
      contentOpenTracked.current = item.id;
      patchLaunchDiagnostics({
        contentOpenTs: Date.now(),
        contentId: item.id,
        seriesId: item.seriesId,
        episodeId: item.episodeId,
      });
    }
  }, [analytics, deepLinkRoute, initialContentId]);

  // The explicit caption choice, the same for every series. Read before the
  // resume point, which only migrates a choice when none is stored.
  useEffect(() => {
    const stored = parseCaptionChoice(readStored("local", CAPTIONS_PREFERENCE_KEY));
    if (stored !== null) setCaptionChoice(stored);
    soundCueShown.current = readStored("session", SOUND_CUE_SESSION_KEY) === "1";
    freeForeverShown.current = readStored("local", FREE_FOREVER_KEY) === "1";
  }, []);

  const showNotice = useCallback((next: Omit<Notice, "id">) => {
    noticeSeq.current += 1;
    setNotice({ ...next, id: noticeSeq.current });
    // One slot at the top: a notice replaces the "Next episode" label instead
    // of being drawn over it (R3A-02). The Continue strip is not in that slot.
    setResumeOffer((offer) => (offer?.reason === "next_episode" ? null : offer));
  }, []);

  /** The layer reports every change it writes; the rail redraws from it. */
  const onRetentionView = useCallback((view: RetentionView) => {
    if (mountedRef.current) setRetentionView(view);
  }, []);
  const trackRetention = useCallback(
    (
      name: "new_episodes_shown" | "new_episodes_open",
      properties: Record<string, string | number | null>,
    ) => analytics.track(name, properties),
    [analytics],
  );

  // Resume from localStorage (non-blocking). Sound always starts off: a saved
  // unmuted preference would make the browser refuse autoplay (PB-3).
  useEffect(() => {
    let cancelled = false;
    void (async () => {
      if (initialContentId) {
        // A shared link resumes only its own series, and never touches the
        // resume points of the others (VIR-2).
        const target = feedRef.current.ordered.find(
          (item) => item.id === initialContentId,
        );
        if (!target) return;
        const saved = await resumeStore.loadForSeries(target.seriesId);
        if (cancelled || !saved) return;
        lastResumeRef.current = saved;
        setCaptionChoice((choice) => migratedCaptionChoice(choice, saved.captionsOn));
        // The shared moment is what the link was for: no offer to go elsewhere.
        if (shareStartMs.current !== null) return;
        if (saved.contentId === initialContentId && isResumable(saved)) {
          // No move and no seek yet: the first play stays an autoplay (MP-2).
          setResumeOffer({
            contentId: saved.contentId,
            positionMs: saved.positionMs,
            reason: "resume",
          });
          patchLaunchDiagnostics({ resumePositionMs: saved.positionMs });
        }
        return;
      }

      const snapshot = await resumeStore.load();
      if (cancelled || !snapshot) return;
      lastResumeRef.current = snapshot;
      setCaptionChoice((choice) => migratedCaptionChoice(choice, snapshot.captionsOn));

      const nextEpisodeIn = (data: FeedData) => (contentId: string) => {
        const saved = data.ordered.find((item) => item.id === contentId);
        return saved ? (data.source.getNextEpisode(saved)?.id ?? null) : null;
      };
      let data = feedRef.current;
      let landing = resumeLanding(snapshot, nextEpisodeIn(data));
      // The first-frame catalog may know neither the saved episode nor the
      // one after it (VIR-1): the full catalog decides.
      const needsCatalog =
        !data.complete &&
        (landing === null
          ? isNearEnd(snapshot)
          : !data.ordered.some((item) => item.id === landing?.contentId));
      if (needsCatalog) {
        const full = await loadCatalog();
        if (cancelled || !full) return;
        data = full;
        landing = resumeLanding(snapshot, nextEpisodeIn(full));
      }
      // Nothing to continue, or the viewer already moved on.
      if (!landing || indexRef.current !== 0) return;
      const target = landing;

      const listed = itemsRef.current.findIndex((item) => item.id === target.contentId);
      if (listed >= 0) {
        // Landing on the slide already on screen is not a move: its first
        // play stays an autoplay and counts toward the first-play target (MP-2).
        if (listed !== indexRef.current) resumeLandingId.current = target.contentId;
        setIndex(listed);
      } else {
        resumeLandingId.current = target.contentId;
        // The page holds only the first frame: the episode comes from the
        // catalog and opens a page of its own.
        const landed = data.ordered.find((item) => item.id === target.contentId);
        if (!landed) return;
        setItems((prev) => pageStartingAt(data.source, landed, prev));
        setIndex(0);
      }
      setResumeOffer(target);
      patchLaunchDiagnostics({ resumePositionMs: target.positionMs });
    })();
    return () => {
      cancelled = true;
    };
  }, [initialContentId, loadCatalog, resumeStore]);

  const current = items[index] ?? null;
  const nextItem = items[index + 1] ?? null;
  const prefetchIds = useMemo(
    () => (items.length > 0 ? getPrefetchIds(items, index) : new Set<string>()),
    [items, index],
  );

  // Warm the next episode's poster. Its first seconds of video are warmed by
  // the player itself (planHlsLoad), never the whole episode.
  useEffect(() => {
    if (!nextItem || typeof document === "undefined") return;
    const posterHref = nextItem.playback.posterReference || nextItem.thumbnailUrl;
    const links: HTMLLinkElement[] = [];

    const add = (rel: string, as: string, href: string, type?: string) => {
      const existing = document.head.querySelector(`link[data-flow-prefetch="${href}"]`);
      if (existing) return;
      const link = document.createElement("link");
      link.rel = rel;
      link.as = as;
      link.href = href;
      link.dataset.flowPrefetch = href;
      if (type) link.type = type;
      document.head.appendChild(link);
      links.push(link);
    };

    add("preload", "image", posterHref);

    return () => {
      for (const link of links) link.remove();
    };
  }, [nextItem]);

  // Open first feed item (non-share) once.
  useEffect(() => {
    if (!current || initialContentId) return;
    if (contentOpenTracked.current === current.id) return;
    contentOpenTracked.current = current.id;
    analytics.track("content_open", {
      content_id: current.id,
      series_id: current.seriesId,
      episode_id: current.episodeId,
      episode_number: current.episodeNumber,
      episode_count: episodeCountOf(feedRef.current.catalog, current),
      source: "feed",
    });
    analytics.track("content_impression", {
      content_id: current.id,
      series_id: current.seriesId,
    });
    patchLaunchDiagnostics({
      contentOpenTs: Date.now(),
      contentId: current.id,
      seriesId: current.seriesId,
      episodeId: current.episodeId,
    });
  }, [analytics, current, initialContentId]);

  useEffect(() => {
    if (!current) return;
    patchLaunchDiagnostics({
      contentId: current.id,
      seriesId: current.seriesId,
      episodeId: current.episodeId,
      contentStatus: current.status,
      width: current.playback.width,
      height: current.playback.height,
      aspectRatio: current.playback.aspectRatio,
      captionTracks: current.captions.filter((t) => t.status === "ready").length,
      captionsOn,
      sourceUri: current.videoUrl,
      prefetchIds: [...prefetchIds],
      anonymousUserId,
      sessionId,
      pageStartTs: perf.get("page_start"),
      timeToFirstPlayMs: perf.timeToFirstPlay(),
    });
  }, [anonymousUserId, captionsOn, current, perf, prefetchIds, sessionId]);

  const persistResume = useCallback(
    async (snapshot: ResumeSnapshot) => {
      if (!shouldPersistResume(lastResumeRef.current, snapshot)) return;
      // The first seconds after a finished episode do not replace it (VIR-1).
      if (keepsFinishedEpisode(lastResumeRef.current, snapshot)) return;
      lastResumeRef.current = snapshot;
      await resumeStore.save(snapshot);
    },
    [resumeStore],
  );

  const emitWatchProgress = useCallback(
    (item: ContentItem, positionMs: number, durationMs: number, force = false) => {
      if (force) progressThrottle.forceNext();
      if (
        !force &&
        !progressThrottle.shouldEmit({
          contentId: item.id,
          positionMs,
          durationMs,
        })
      ) {
        return;
      }
      const completion =
        durationMs > 0 ? Math.min(100, (positionMs / durationMs) * 100) : 0;
      analytics.track("watch_progress", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        episode_number: item.episodeNumber,
        episode_count: episodeCountOf(feedRef.current.catalog, item),
        position_ms: Math.round(positionMs),
        duration_ms: Math.round(durationMs),
        completion_percentage: Math.round(completion),
        session_id: sessionId,
        anonymous_user_id: anonymousUserId,
      });
    },
    [analytics, anonymousUserId, progressThrottle, sessionId],
  );

  /** series_complete once per episode, only for the series' last one (MP-7). */
  const trackSeriesComplete = useCallback(
    (item: ContentItem, via: "ended" | "swipe") => {
      if (seriesCompleteSent.current.has(item.id)) return;
      seriesCompleteSent.current.add(item.id);
      analytics.track("series_complete", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_number: item.episodeNumber,
        episode_count: episodeCountOf(feedRef.current.catalog, item),
        via,
      });
    },
    [analytics],
  );

  const handleIndexChange = useCallback(
    (
      next: number,
      kind: PendingTransition["kind"] = "swipe",
      nextItems: ContentItem[] = items,
      gestureStartedAt?: number,
    ) => {
      // Same position with a different list is a move (placeStory can put the
      // next story where the viewer already is).
      if (next === index && nextItems === items) return;
      const from = items[index];
      if (from) {
        const watched = progressStore.get(from.id);
        emitWatchProgress(from, watched * from.durationMs, from.durationMs, true);
        analytics.track("episode_leave", {
          content_id: from.id,
          series_id: from.seriesId,
          episode_id: from.episodeId,
          completion_percentage: Math.round(watched * 100),
        });
        // Leaving the last episode after watching nearly all of it finishes the series.
        if (
          finishedLastEpisode(
            from.episodeNumber,
            episodeCountOf(feedRef.current.catalog, from),
            watched,
          )
        ) {
          trackSeriesComplete(from, "swipe");
        }
        const watchedPct = watched * 100;
        if (watchedPct > 0 && watchedPct < 40) {
          analytics.track("video_skipped", {
            content_id: from.id,
            completion_percentage: Math.round(watchedPct),
          });
        }
      }
      const to = nextItems[next];
      if (kind === "swipe") {
        analytics.track("feed_swipe", {
          direction: next > index ? "next" : "previous",
          from_content_id: items[index]?.id ?? null,
          to_content_id: to?.id ?? null,
        });
      }
      if (to && contentOpenTracked.current !== to.id) {
        contentOpenTracked.current = to.id;
        analytics.track("content_open", {
          content_id: to.id,
          series_id: to.seriesId,
          episode_id: to.episodeId,
          episode_number: to.episodeNumber,
          episode_count: episodeCountOf(feedRef.current.catalog, to),
          source: kind === "swipe" ? "feed_swipe" : kind,
        });
        analytics.track("content_impression", {
          content_id: to.id,
          series_id: to.seriesId,
        });
      }
      perf.mark("episode_transition_started");
      transitionRef.current = to
        ? { toContentId: to.id, kind, startedAt: gestureStartedAt ?? performance.now() }
        : null;
      setSeriesEnded(null);
      setResumeOffer(null);
      setSeekToMs(null);
      setAutoplayBlocked(false);
      setPlaybackFailure(null);
      progressThrottle.reset();
      if (nextItems !== items) setItems(nextItems);
      setIndex(next);
      // A viewer who swipes has chosen a second episode: the moment the apps
      // they know start asking for money, and the only moment we say we never
      // will. Once per device, never over anything else, never at the cold
      // open, and never before the sound cue has had its turn.
      if (
        kind === "swipe" &&
        !freeForeverShown.current &&
        soundCueShown.current &&
        !cueBlockedRef.current
      ) {
        freeForeverShown.current = true;
        writeStored("local", FREE_FOREVER_KEY, "1");
        showNotice({ kind: "free_forever", text: FREE_FOREVER_LINE });
        analytics.track("free_forever_shown", { content_id: to?.id ?? null });
      }
    },
    [
      analytics,
      emitWatchProgress,
      index,
      items,
      perf,
      progressStore,
      progressThrottle,
      showNotice,
      trackSeriesComplete,
    ],
  );

  /** A swipe (scroll gesture or key): latency counts from the gesture's start. */
  const handleScrollerIndexChange = useCallback(
    (next: number, gestureStartedAt?: number) =>
      handleIndexChange(next, "swipe", items, gestureStartedAt),
    [handleIndexChange, items],
  );

  // A failed episode stays on screen long enough to read why, then the feed
  // moves on: to the next episode of the series when there is one (PB-5).
  const skipFailedRef = useRef<(failure: PlaybackFailure) => void>(() => undefined);
  skipFailedRef.current = (failure: PlaybackFailure) => {
    const active = items[index];
    if (!active || active.id !== failure.contentId) return;
    const moveOn = (target: () => void) => {
      analytics.track("playback_error_skip", {
        content_id: active.id,
        series_id: active.seriesId,
        episode_id: active.episodeId,
      });
      if (failure.connection) connectionSkipsRef.current += 1;
      pendingSkipRef.current = null;
      target();
    };
    const placed = placeNextInSeries(feedRef.current.source, items, index);
    if (placed.kind === "next_in_series") {
      moveOn(() => handleIndexChange(placed.nextIndex, "error_skip", placed.items));
      return;
    }
    if (index < items.length - 1) {
      moveOn(() => handleIndexChange(index + 1, "error_skip"));
      return;
    }
    // Last listed slide: the error stays up while the page is built, and the
    // skip happens as soon as a slide exists after it.
    if (
      feedExhausted(
        feedRef.current.complete,
        feedRef.current.ordered.length,
        items.length,
      )
    ) {
      pendingSkipRef.current = null;
      setPlaybackFailure({ ...failure, hold: "end" });
      return;
    }
    pendingSkipRef.current = failure.contentId;
    void ensureFeedPage();
  };
  useEffect(() => {
    if (
      !playbackFailure ||
      playbackFailure.hold ||
      current?.id !== playbackFailure.contentId
    ) {
      return;
    }
    const failure = playbackFailure;
    const timer = window.setTimeout(
      () => skipFailedRef.current(failure),
      ERROR_SKIP_DELAY_MS,
    );
    return () => window.clearTimeout(timer);
  }, [current?.id, playbackFailure]);
  // A skip that waited at the last slide runs once the page has grown, or
  // settles on a visible end when the catalog has nothing more.
  useEffect(() => {
    const pending = pendingSkipRef.current;
    if (
      !pending ||
      !playbackFailure ||
      playbackFailure.hold ||
      playbackFailure.contentId !== pending
    ) {
      return;
    }
    if (current?.id !== pending) {
      pendingSkipRef.current = null;
      return;
    }
    if (index < items.length - 1 || pageReady) skipFailedRef.current(playbackFailure);
  }, [current?.id, feed.complete, index, items.length, pageReady, playbackFailure]);

  const handleTimeUpdate = (
    item: ContentItem,
    positionMs: number,
    durationMs: number,
  ) => {
    progressStore.set(item.id, durationMs > 0 ? positionMs / durationMs : 0);
    patchLaunchDiagnostics({
      currentTimeMs: positionMs,
      durationMs,
    });
    emitWatchProgress(item, positionMs, durationMs);
    void persistResume({
      contentId: item.id,
      seriesId: item.seriesId,
      episodeId: item.episodeId,
      positionMs,
      durationMs: durationMs || item.durationMs,
      muted,
      // Only an explicit choice is saved: the muted default is not one.
      captionsOn: captionChoiceRef.current === true,
      updatedAt: Date.now(),
      completed: false,
    });
  };

  const handleEnded = (item: ContentItem) => {
    emitWatchProgress(item, item.durationMs, item.durationMs, true);
    // Watched to the end: the series page can say so without inferring it
    // from a resume point (retentionState.ts).
    const finishedAt = Date.now();
    void ensureRetention().then((loaded) =>
      loaded?.runtime.markWatched(
        {
          contentId: item.id,
          seriesId: item.seriesId,
          episodeNumber: item.episodeNumber,
        },
        finishedAt,
      ),
    );
    analytics.track("episode_complete", {
      content_id: item.id,
      series_id: item.seriesId,
      episode_id: item.episodeId,
      episode_number: item.episodeNumber,
      episode_count: episodeCountOf(feedRef.current.catalog, item),
    });
    install.episodeFinished();
    void persistResume({
      contentId: item.id,
      seriesId: item.seriesId,
      episodeId: item.episodeId,
      positionMs: item.durationMs,
      durationMs: item.durationMs,
      muted,
      // Only an explicit choice is saved: the muted default is not one.
      captionsOn: captionChoiceRef.current === true,
      updatedAt: Date.now(),
      completed: true,
    });
    void recommendationFor(feedRef.current).recordSignal({
      contentId: item.id,
      seriesId: item.seriesId,
      genres: item.genres,
      tropes: item.tropes,
      language: item.language,
      action: "complete",
      watchDurationMs: item.durationMs,
      completionPercentage: 100,
      now: Date.now(),
    });

    void (async () => {
      let placed = placeNextInSeries(
        feedRef.current.source,
        itemsRef.current,
        indexRef.current,
      );
      if (placed.kind === "series_complete" && !feedRef.current.complete) {
        // The first-frame catalog may not know the next episode yet.
        const data = await loadCatalog();
        if (data)
          placed = placeNextInSeries(data.source, itemsRef.current, indexRef.current);
      }
      // The viewer moved on meanwhile: nothing to continue.
      if (!mountedRef.current || itemsRef.current[indexRef.current]?.id !== item.id)
        return;

      if (placed.kind === "next_in_series") {
        const continueKey = `${item.id}->${placed.next.id}`;
        if (lastContinueKey.current !== continueKey) {
          lastContinueKey.current = continueKey;
          analytics.track("series_continue", {
            content_id: item.id,
            series_id: item.seriesId,
            next_content_id: placed.next.id,
            next_episode_id: placed.next.episodeId,
          });
        }
        perf.mark("episode_transition_started");
        transitionRef.current = {
          toContentId: placed.next.id,
          kind: "auto_continue",
          startedAt: performance.now(),
        };
        setSeriesEnded(null);
        setSeekToMs(null);
        setPlaybackFailure(null);
        if (placed.items !== itemsRef.current) setItems(placed.items);
        setIndex(placed.nextIndex);
        return;
      }
      // Only the last episode completes a series; a missing or unready next
      // episode is reported as what it is (MP-7).
      const ending = classifySeriesEnd(
        item.episodeNumber,
        episodeCountOf(feedRef.current.catalog, item),
      );
      if (ending === "series_complete") {
        trackSeriesComplete(item, "ended");
      } else {
        analytics.track("series_unavailable_next", {
          content_id: item.id,
          series_id: item.seriesId,
          episode_number: item.episodeNumber,
          episode_count: episodeCountOf(feedRef.current.catalog, item),
        });
      }
      setSeriesEnded(ending);
    })();
  };

  /**
   * rail: the episode on screen, at the moment shared (OPP-02).
   * series_end: the story from its first episode, never the finale.
   */
  const handleShare = useCallback(
    async (item: ContentItem, source: "rail" | "series_end") => {
      // Inlined at build: every share points at the site, whatever host served
      // this page (VIR-8).
      const origin = shareOrigin(
        process.env.NEXT_PUBLIC_SITE_URL,
        typeof window !== "undefined" ? window.location.origin : "",
      );
      const shareId = createShareId();
      const target =
        source === "series_end" ? storyShareTarget(item, feedRef.current.ordered) : item;
      const startSeconds =
        source === "rail"
          ? shareStartSeconds(
              progressStore.get(item.id) * item.durationMs,
              item.durationMs,
            )
          : null;
      const url = buildShareUrl(feedRef.current.catalog, target, origin, {
        utmSource: "share",
        utmMedium: "social",
        ...(source === "series_end" ? { utmCampaign: "series_end" } : {}),
        shareId,
        startSeconds,
      });
      if (!url) return;
      analytics.track("share_open", {
        content_id: target.id,
        series_id: target.seriesId,
        episode_id: target.episodeId,
        share_id: shareId,
        source,
        start_seconds: startSeconds,
      });
      if (typeof navigator !== "undefined" && typeof navigator.share === "function") {
        try {
          await navigator.share({ ...shareMessage(target), url });
          analytics.track("share_native", {
            content_id: target.id,
            share_id: shareId,
          });
          return;
        } catch (error) {
          // Closing the share sheet is a choice: the clipboard stays untouched (VIR-3).
          if (error instanceof DOMException && error.name === "AbortError") {
            analytics.track("share_cancel", { content_id: target.id, share_id: shareId });
            return;
          }
          // Any other refusal (no sheet in this browser): copy the link instead.
        }
      }
      try {
        if (typeof navigator === "undefined" || !navigator.clipboard) {
          throw new Error("clipboard unavailable");
        }
        await navigator.clipboard.writeText(url);
        analytics.track("share_copy", {
          content_id: target.id,
          share_id: shareId,
        });
        showNotice({ kind: "share_copied", text: "Link copied" });
      } catch {
        analytics.track("share_copy_failed", {
          content_id: target.id,
          share_id: shareId,
        });
        showNotice({ kind: "share_failed", text: "Couldn’t copy the link", detail: url });
      }
    },
    [analytics, progressStore, showNotice],
  );

  const handleIntentChip = useCallback(
    async (chipId: IntentChipId) => {
      const tapped = itemsRef.current[indexRef.current];
      const data = (await loadCatalog()) ?? feedRef.current;
      const resolution = await intentFor(data).resolveChip(chipId, {
        contentId: tapped?.id ?? null,
        seriesId: tapped?.seriesId ?? null,
        genres: tapped?.genres ?? [],
        tropes: tapped?.tropes ?? [],
      });
      setIntentOpen(false);

      const byId = new Map(data.ordered.map((item) => [item.id, item]));
      const intentItems = resolution.candidates
        .map((candidate) => byId.get(candidate.contentId))
        .filter((entry): entry is ContentItem => Boolean(entry));

      // The fetch can take seconds: the page is built around the episode on
      // screen now, not the one on screen when the chip was tapped (R2).
      const headIndex = indexRef.current;
      const head = itemsRef.current[headIndex];
      const reordered = intentItems.length > 0 && head !== undefined;
      // The sheet closing is not an answer: say what changed, and only what did (UX-09).
      showNotice({
        kind: "intent",
        text: intentConfirmation(chipId, reordered ? intentItems.length : 0),
      });
      if (!reordered) return;
      userReorderedRef.current = true;
      setItems((prev) => applyIntentPage(prev, head.id, intentItems));
      setIndex(0);
    },
    [intentFor, loadCatalog, showNotice],
  );

  const showGate = shouldShowPlayGate(autoplayBlocked, userStartedPlayback);

  /** wasMuted: the state the viewer changed; the new one is its opposite. */
  const setSound = (wasMuted: boolean, source: "surface" | "rail" | "key") => {
    const nextMuted = !wasMuted;
    mutedRef.current = nextMuted;
    setMuted(nextMuted);
    setNotice((shown) => (shown?.kind === "sound" ? null : shown));
    // A viewer who found the sound needs no cue later, even muted again.
    if (!nextMuted && !soundCueShown.current) {
      soundCueShown.current = true;
      writeStored("session", SOUND_CUE_SESSION_KEY, "1");
    }
    analytics.track("sound_toggled", {
      content_id: current?.id ?? null,
      muted: nextMuted,
      source,
      captions_on: effectiveCaptions(captionChoiceRef.current, nextMuted, true),
    });
  };

  // "Tap for sound", once per browser session, for the first episode that
  // plays muted with nothing else on screen (UX-02).
  /**
   * The strip slot belongs first to what the viewer asked for: a resume offer,
   * the end of a series, the Tune sheet, an error, the tap-to-play gate. The
   * "new since you were here" line waits for all of them.
   */
  const stripSlotTaken =
    showGate ||
    seriesEnded !== null ||
    intentOpen ||
    resumeOffer !== null ||
    playbackFailure !== null;
  const cueBlocked = stripSlotTaken || notice !== null;
  // Read from a swipe handler, which sees the screen as it was before the
  // move. The free-forever line also waits for the news strip: two messages at
  // once is one too many, and it has the next swipe.
  cueBlockedRef.current = cueBlocked || newsCovering;
  // The one-time invitation to install (A11Y-04): after real engagement,
  // never over anything else on screen (installRules.ts), the news strip
  // included.
  const install = useInstallOffer(analytics, cueBlocked || newsCovering);

  /** The news line took the viewer to the first episode they had not seen. */
  const openFromNews = (target: ContentItem) => {
    const listed = items.findIndex((item) => item.id === target.id);
    if (listed >= 0) {
      handleIndexChange(listed, "next_story");
      return;
    }
    // Not on this page of the feed: the episode and the one after it open a
    // page of their own, as a resume landing does.
    handleIndexChange(0, "next_story", pageStartingAt(feed.source, target, items));
  };
  useEffect(() => {
    if (
      !shouldShowSoundCue({
        muted,
        playing: current !== null && framedContentId === current.id,
        alreadyShown: soundCueShown.current,
        blocked: cueBlocked,
        sinceFirstFrameMs:
          current !== null && framedAtRef.current?.contentId === current.id
            ? performance.now() - framedAtRef.current.at
            : null,
      })
    ) {
      return;
    }
    soundCueShown.current = true;
    writeStored("session", SOUND_CUE_SESSION_KEY, "1");
    showNotice({ kind: "sound", text: "Tap for sound" });
    analytics.track("sound_cue_shown", { content_id: current?.id ?? null });
  }, [analytics, cueBlocked, current, framedContentId, muted, showNotice]);

  // Each notice leaves on its own; the sound cue also at the first touch or key.
  useEffect(() => {
    if (!notice) return;
    const shown = notice.id;
    const kind = notice.kind;
    const hide = () => setNotice((value) => (value?.id === shown ? null : value));
    let timer = 0;
    // The link shown when copying failed stays while it is being copied (R3A-04).
    const expire = () => {
      const pill = document.querySelector("[data-notice]");
      const selection = window.getSelection();
      const held = shouldHoldNotice({
        kind,
        focusInside: pill !== null && pill.contains(document.activeElement),
        selectionInside:
          pill !== null &&
          selection !== null &&
          !selection.isCollapsed &&
          pill.contains(selection.anchorNode),
      });
      if (held) {
        timer = window.setTimeout(expire, NOTICE_HOLD_RECHECK_MS);
        return;
      }
      hide();
    };
    timer = window.setTimeout(expire, NOTICE_MS[kind]);
    if (kind !== "sound") return () => window.clearTimeout(timer);
    window.addEventListener("pointerdown", hide, true);
    window.addEventListener("keydown", hide, true);
    return () => {
      window.clearTimeout(timer);
      window.removeEventListener("pointerdown", hide, true);
      window.removeEventListener("keydown", hide, true);
    };
  }, [notice]);

  // "Next episode" is a label, not a control: it fades by itself (B2-UPNEXT).
  useEffect(() => {
    if (resumeOffer?.reason !== "next_episode") return;
    const offer = resumeOffer;
    const timer = window.setTimeout(
      () => setResumeOffer((value) => (value === offer ? null : value)),
      UP_NEXT_LABEL_MS,
    );
    return () => window.clearTimeout(timer);
  }, [resumeOffer]);

  const episodeCounts = useMemo(
    () => new Map(feed.catalog.series.map((series) => [series.id, series.totalEpisodes])),
    [feed.catalog],
  );
  const positionOf = (item: ContentItem) =>
    episodePosition(item.episodeNumber, episodeCounts.get(item.seriesId) ?? null).text;

  // Screen readers hear where a swipe or a key landed, politely (A11Y-07).
  const [episodeAnnounced, setEpisodeAnnounced] = useState("");
  const announcedFrom = useRef<string | null>(null);
  const currentAnnouncement = current
    ? episodeAnnouncement(
        current.seriesTitle,
        episodePosition(
          current.episodeNumber,
          episodeCounts.get(current.seriesId) ?? null,
        ).label,
      )
    : "";
  useEffect(() => {
    const currentId = current?.id ?? null;
    if (shouldAnnounceEpisode(announcedFrom.current, currentId)) {
      setEpisodeAnnounced(currentAnnouncement);
    }
    announcedFrom.current = currentId;
    // The words follow the episode: a catalog that fills in the total later is not a change.
  }, [current?.id]);

  const nextStory = useMemo(
    () => (seriesEnded ? pickNextStory(items, index, feed.ordered) : null),
    [feed.ordered, index, items, seriesEnded],
  );
  // What the end of a series offered, once per ending: the handoff rate is
  // next_story_open over next_story_offered.
  const offeredFor = useRef<string | null>(null);
  useEffect(() => {
    if (!seriesEnded || !current) {
      offeredFor.current = null;
      return;
    }
    if (offeredFor.current === current.id) return;
    offeredFor.current = current.id;
    analytics.track("next_story_offered", {
      content_id: current.id,
      series_id: current.seriesId,
      kind: seriesEnded,
      next_content_id: nextStory?.id ?? null,
      next_series_id: nextStory?.seriesId ?? null,
    });
  }, [analytics, current, nextStory, seriesEnded]);

  const handlePlayGate = () => {
    if (!firstPlayMarked.current && gateTapAt.current === null) {
      gateTapAt.current = performance.now();
    }
    setUserStartedPlayback(true);
    setAutoplayBlocked(false);
    analytics.track("first_play_attempted", {
      session_id: sessionId,
      content_id: items[index]?.id ?? null,
      source: "play_gate",
    });
    const video = document.querySelector<HTMLVideoElement>(
      `[data-content-id="${items[index]?.id ?? ""}"] video`,
    );
    if (video) {
      void video.play().catch(() => undefined);
    }
  };

  playToggleRef.current = () => {
    const video = document.querySelector<HTMLVideoElement>(
      `[data-content-id="${items[index]?.id ?? ""}"] video`,
    );
    if (!video) return;
    if (video.paused) {
      void video.play().catch(() => setAutoplayBlocked(true));
    } else {
      video.pause();
    }
  };

  const handlerImpl: FeedItemHandlers = {
    onToggleMute: (source) => setSound(mutedRef.current, source),
    onUnmute: () => {
      if (mutedRef.current) setSound(true, "surface");
    },
    onToggleCaptions: () => {
      // The explicit choice wins from now on, whatever the sound does, and is
      // remembered on this device (decision 3).
      // Nothing to toggle on an episode without captions: no invisible "off"
      // is saved for every series (R3A-03).
      const next = nextCaptionChoice(
        captionChoiceRef.current,
        mutedRef.current,
        current?.captionsAvailable ?? false,
      );
      if (next === null) return;
      captionChoiceRef.current = next;
      setCaptionChoice(next);
      writeStored("local", CAPTIONS_PREFERENCE_KEY, serializeCaptionChoice(next));
      analytics.track("caption_toggled", {
        session_id: sessionId,
        captions_on: next,
        muted: mutedRef.current,
        content_id: current?.id ?? null,
      });
    },
    onTogglePlayPause: () => playToggleRef.current(),
    onPlayGate: handlePlayGate,
    onLike: (item) => {
      const liked = !likedIds.has(item.id);
      const likedAt = Date.now();
      // Tapped before the chunk is in: the rail answers now, and the device
      // records what the viewer meant the moment it arrives (applyLike).
      if (!retentionRef.current) {
        setRetentionView((view) => ({ ...view, liked: flipped(view.liked, item.id) }));
      }
      void ensureRetention().then((loaded) => {
        if (!loaded) return;
        onRetentionView(
          loaded.mod.applyLike(
            loaded.runtime,
            { contentId: item.id, seriesId: item.seriesId },
            liked,
            likedAt,
          ),
        );
      });
      analytics.track("like", {
        content_id: item.id,
        series_id: item.seriesId,
        liked,
      });
      void recommendationFor(feedRef.current).recordSignal({
        contentId: item.id,
        seriesId: item.seriesId,
        genres: item.genres,
        tropes: item.tropes,
        language: item.language,
        action: "like",
        watchDurationMs: 0,
        completionPercentage: 0,
        now: Date.now(),
      });
    },
    onFollow: (item) => {
      const following = !followingIds.has(item.seriesId);
      const seriesSlug = seriesSlugOf(feedRef.current.catalog, item.seriesId);
      const followedAt = Date.now();
      if (!retentionRef.current) {
        setRetentionView((view) => ({
          ...view,
          following: flipped(view.following, item.seriesId),
        }));
      }
      // What the series has now is recorded with it (applyFollow): the news
      // counts from the promise, not from episode 1.
      void ensureRetention().then((loaded) => {
        if (!loaded) return;
        onRetentionView(
          loaded.mod.applyFollow(
            loaded.runtime,
            { seriesId: item.seriesId, seriesSlug },
            following,
            feedRef.current,
            followedAt,
          ),
        );
      });
      analytics.track("follow", {
        content_id: item.id,
        series_id: item.seriesId,
        following,
        episode_count: episodeCountOf(feedRef.current.catalog, item),
      });
      void recommendationFor(feedRef.current).recordSignal({
        contentId: item.id,
        seriesId: item.seriesId,
        genres: item.genres,
        tropes: item.tropes,
        language: item.language,
        action: "follow",
        watchDurationMs: 0,
        completionPercentage: 0,
        now: Date.now(),
      });
    },
    onShare: (item) => {
      void handleShare(item, "rail");
    },
    onTune: () => {
      if (!flags.isEnabled("INTENT_LAYER")) return;
      analytics.track("intent_open", { session_id: sessionId });
      setIntentOpen(true);
    },
    onMetadataReady: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("content_metadata_ready");
    },
    onPosterVisible: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("poster_visible");
    },
    onLoadStart: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("video_load_started");
    },
    onCanPlay: (item) => {
      if (item.id !== current?.id) return;
      perf.mark("video_can_play");
      analytics.track("video_ready", {
        session_id: sessionId,
        content_id: item.id,
      });
    },
    onTimeUpdate: handleTimeUpdate,
    onEnded: handleEnded,
    onError: (item, code, reason, connection) => {
      const hold = failureHoldFor(connection, connectionSkipsRef.current);
      analytics.track("playback_error", {
        session_id: sessionId,
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        error_code: code,
        reason,
        connection,
        held: hold !== null,
      });
      // Only the episode on screen moves the feed; a neighbour never does
      // (PB-4, R3). The skip waits until the error has been read (PB-5); after
      // several connection failures in a row it waits for the viewer instead.
      if (item.id !== current?.id) return;
      scheduleFeedPage();
      pendingSkipRef.current = null;
      setPlaybackFailure({ contentId: item.id, connection, hold });
    },
    onRetry: (item) => {
      analytics.track("playback_retry", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
      });
      // A neighbour retried by the online event never clears the failure on screen.
      if (pendingSkipRef.current === item.id) pendingSkipRef.current = null;
      setPlaybackFailure((failure) => (failure?.contentId === item.id ? null : failure));
    },
    onPlayAttempt: (item) => {
      patchLaunchDiagnostics({
        autoplayAttempted: true,
        playAttemptTs: Date.now(),
        playerState: "loading",
      });
      if (firstAttemptMarked.current) return;
      firstAttemptMarked.current = true;
      analytics.track("first_play_attempted", {
        content_id: item.id,
        source: "autoplay",
      });
    },
    onPlay: () => {
      // Playback requested and unpaused; no frame yet, so no speed metric here.
      setAutoplayBlocked(false);
      setUserStartedPlayback(true);
    },
    onMutedFallback: (item) => {
      mutedRef.current = true;
      setMuted(true);
      analytics.track("autoplay_muted_fallback", {
        content_id: item.id,
        series_id: item.seriesId,
      });
    },
    onSeekApplied: (item) => {
      if (item.id !== current?.id) return;
      // Applied once: a later canplay must never replay it (PB-2).
      setSeekToMs(null);
    },
    onPlaying: (item, info) => {
      if (item.id !== current?.id) return;
      if (framedAtRef.current?.contentId !== item.id) {
        framedAtRef.current = { contentId: item.id, at: performance.now() };
      }
      setFramedContentId(item.id);
      setAutoplayBlocked(false);
      setUserStartedPlayback(true);
      patchLaunchDiagnostics({
        playerState: "playing",
        autoplayBlocked: false,
        contentId: item.id,
        seriesId: item.seriesId,
        episodeId: item.episodeId,
        sourceUri: item.videoUrl,
      });
      if (info.firstFrame) perf.mark("episode_first_frame_played");
      // An episode plays: the connection works, skipping is allowed again.
      connectionSkipsRef.current = 0;
      if (info.firstFrame && !firstPlayMarked.current) {
        firstPlayMarked.current = true;
        perf.mark("video_play_started");
        perf.mark("first_meaningful_play");
        const ttfp = perf.timeToFirstPlay();
        const startMode = firstPlayStartMode({
          gateTapped: gateTapAt.current !== null,
          resumeLandingId: resumeLandingId.current,
          contentId: item.id,
        });
        patchLaunchDiagnostics({
          firstMeaningfulPlayTs: perf.get("first_meaningful_play"),
          timeToFirstPlayMs: ttfp,
        });
        analytics.track("first_meaningful_play", {
          content_id: item.id,
          series_id: item.seriesId,
          episode_id: item.episodeId,
          time_to_first_play: ttfp,
          // docs/standard.md §3 judges time_to_first_play on start_mode = autoplay.
          start_mode: startMode,
          autoplay_blocked: autoplayBlockedBeforeFirstPlay.current,
          gate_tap_to_play_ms:
            gateTapAt.current === null
              ? null
              : Math.round(performance.now() - gateTapAt.current),
          frame_source: info.frameSource,
          page_start_ts: perf.get("page_start"),
          video_load_started_ts: perf.get("video_load_started"),
          video_can_play_ts: perf.get("video_can_play"),
          first_meaningful_play_ts: perf.get("first_meaningful_play"),
        });
        const acquisition = loadAcquisitionContext();
        if (
          !sharePlayTracked.current &&
          (acquisition?.shareId || acquisition?.utmSource === "share")
        ) {
          sharePlayTracked.current = true;
          analytics.track("share_play", {
            content_id: item.id,
            series_id: item.seriesId,
            share_id: acquisition.shareId,
            utm_source: acquisition.utmSource,
          });
        }
        // The episode is playing: the rest of the feed can now be prepared.
        scheduleFeedPage();
      }
      // Swipe latency ends at the first real frame of the episode swiped to,
      // measured on one clock (MP-1).
      const transition = transitionRef.current;
      const transitionMs =
        info.firstFrame && transition?.toContentId === item.id
          ? Math.round(performance.now() - transition.startedAt)
          : null;
      if (info.firstFrame && transition?.toContentId === item.id)
        transitionRef.current = null;
      analytics.track("play", {
        content_id: item.id,
        series_id: item.seriesId,
        episode_id: item.episodeId,
        first_frame: info.firstFrame,
        frame_source: info.frameSource,
        swipe_to_play_ms: transition?.kind === "swipe" ? transitionMs : null,
        transition_kind: transitionMs === null ? null : (transition?.kind ?? null),
        transition_to_play_ms: transitionMs,
      });
    },
    onPause: () => {
      patchLaunchDiagnostics({ playerState: "paused" });
      analytics.track("pause", {
        content_id: current?.id ?? null,
      });
    },
    onBufferingStart: (item) => {
      patchLaunchDiagnostics({ playerState: "buffering" });
      analytics.track("buffer_start", {
        content_id: item.id,
      });
    },
    onBufferingEnd: (item) => {
      patchLaunchDiagnostics({ playerState: "playing" });
      analytics.track("buffer_end", {
        content_id: item.id,
      });
    },
    onAutoplayBlocked: () => {
      // Waiting for a tap: the main thread is free for the feed page.
      scheduleFeedPage();
      if (!firstPlayMarked.current) autoplayBlockedBeforeFirstPlay.current = true;
      if (!userStartedPlayback) {
        setAutoplayBlocked(true);
        patchLaunchDiagnostics({
          autoplayBlocked: true,
          playerState: "autoplay_blocked",
        });
      }
    },
  };
  const latestHandlers = useRef(handlerImpl);
  latestHandlers.current = handlerImpl;
  const [handlers] = useState(() => createStableHandlers(latestHandlers));

  if (items.length === 0) {
    return (
      <main className={styles.root}>
        <FeedStage>
          <p className={styles.empty}>Finding something great…</p>
        </FeedStage>
      </main>
    );
  }

  return (
    <main className={styles.root}>
      <FeedStage>
        <FeedScroller
          items={items}
          index={index}
          onIndexChange={handleScrollerIndexChange}
          muted={muted}
          captionsOn={captionsOn}
          episodeCounts={episodeCounts}
          coveredContentId={
            resumeOffer && resumeOffer.reason !== "next_episode"
              ? resumeOffer.contentId
              : newsCovering
                ? (current?.id ?? null)
                : null
          }
          likedIds={likedIds}
          followingIds={followingIds}
          seekToMs={seekToMs}
          showPlayGate={showGate}
          failureHold={
            playbackFailure && playbackFailure.contentId === current?.id
              ? playbackFailure.hold
              : null
          }
          prefetchIds={prefetchIds}
          locale={locale}
          progressStore={progressStore}
          handlers={handlers}
          modalOpen={intentOpen}
        />

        <div
          className={styles.visuallyHidden}
          role="status"
          aria-live="polite"
          aria-atomic="true"
          data-episode-announcer="true"
        >
          {episodeAnnounced}
        </div>

        {resumeOffer &&
        current?.id === resumeOffer.contentId &&
        resumeOffer.reason === "next_episode" ? (
          <UpNextLabel
            seriesTitle={current.seriesTitle}
            episodeLabel={positionOf(current)}
          />
        ) : null}

        {resumeOffer &&
        current?.id === resumeOffer.contentId &&
        resumeOffer.reason !== "next_episode" ? (
          <ContinueStrip
            seriesTitle={current.seriesTitle}
            episodeLabel={positionOf(current)}
            onContinue={() => {
              // Seeks right away when the episode is loaded (PB-2).
              if (resumeOffer.positionMs > 0) setSeekToMs(resumeOffer.positionMs);
              setResumeOffer(null);
              analytics.track("episode_resume_started", {
                session_id: sessionId,
                content_id: resumeOffer.contentId,
                position_ms: resumeOffer.positionMs,
                reason: resumeOffer.reason,
              });
              const resumeIndex = items.findIndex(
                (item) => item.id === resumeOffer.contentId,
              );
              if (resumeIndex >= 0 && resumeIndex !== index) setIndex(resumeIndex);
            }}
          />
        ) : null}

        {retentionLoaded ? (
          <retentionLoaded.mod.RetentionLayer
            runtime={retentionLoaded.runtime}
            ordered={feed.ordered}
            complete={feed.complete}
            currentId={current?.id ?? null}
            blocked={stripSlotTaken}
            onViewChange={onRetentionView}
            onOpenEpisode={openFromNews}
            onVisibleChange={setNewsCovering}
            track={trackRetention}
          />
        ) : null}

        {seriesEnded && current && seriesEnd.module ? (
          <seriesEnd.module.SeriesEnd
            seriesTitle={current.seriesTitle}
            kind={seriesEnded}
            position={
              seriesEnded === "series_complete" && episodeCounts.get(current.seriesId)
                ? `${episodeCounts.get(current.seriesId)} episodes`
                : positionOf(current)
            }
            following={followingIds.has(current.seriesId)}
            nextStory={
              nextStory
                ? {
                    contentId: nextStory.id,
                    seriesTitle: nextStory.seriesTitle,
                    hook: nextStory.hook.replace(/\n/g, " "),
                    posterUrl:
                      nextStory.playback.posterReference || nextStory.thumbnailUrl,
                    position: positionOf(nextStory),
                  }
                : null
            }
            onShare={() => void handleShare(current, "series_end")}
            onFollow={() => handlers.onFollow(current)}
            onNextStory={() => {
              if (!nextStory) return;
              analytics.track("next_story_open", {
                content_id: nextStory.id,
                series_id: nextStory.seriesId,
                from_content_id: current.id,
                from_series_id: current.seriesId,
              });
              // One explicit tap, never a countdown (docs/decisions.md, Prompt D).
              const placed = placeStory(items, index, nextStory);
              handleIndexChange(placed.index, "next_story", placed.items);
            }}
            onClose={() => setSeriesEnded(null)}
          />
        ) : null}

        <NoticePill notice={notice} durationMs={notice ? NOTICE_MS[notice.kind] : 0} />

        {install.offer && !cueBlocked ? (
          <InstallOffer
            platform={install.offer}
            onAccept={install.accept}
            onDismiss={install.dismiss}
          />
        ) : null}

        {intentSheet.module ? (
          <intentSheet.module.IntentSheet
            open={intentOpen}
            onClose={() => setIntentOpen(false)}
            onSelect={(chipId) => {
              analytics.track("intent_select", { chip_id: chipId });
              void handleIntentChip(chipId);
            }}
          />
        ) : null}

        {diagOpen ? (
          <LaunchDiagPanel
            onClose={() => setDiagOpen(false)}
            transport={getAnalyticsTransport()}
          />
        ) : null}
      </FeedStage>
    </main>
  );
}
