import type { Metadata } from "next";

import { BrandMark } from "@/features/platform/BrandMark";
import { OfflineRetry } from "@/features/platform/OfflineRetry";
import styles from "@/features/platform/platform.module.css";

export const metadata: Metadata = {
  title: "Offline",
  description: "No connection right now.",
  // Never a search result, whatever the launch switch says.
  robots: { index: false, follow: false },
};

/**
 * What the service worker shows when a page cannot be reached
 * (public/sw.js is generated by scripts/finish-export.mjs). It is precached
 * with its styles and fonts, so it draws without a network. It is never a
 * stale copy of the feed: pages are always asked of the network first.
 */
export default function OfflinePage() {
  return (
    <main className={styles.offlineRoot} data-offline-page="true">
      <div className={styles.offlineColumn}>
        <BrandMark />
        <div className={styles.offlineMessage}>
          <p className={styles.offlineKicker}>
            <span className={styles.offlineDot} aria-hidden="true" />
            No connection
          </p>
          <h1 className={styles.offlineTitle}>You’re offline.</h1>
          <p className={styles.offlineBody}>
            Your stories keep your place. This page starts again by itself when the
            connection is back.
          </p>
        </div>
        <OfflineRetry />
      </div>
    </main>
  );
}
